import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

final localeControllerProvider =
    AsyncNotifierProvider<LocaleController, Locale?>(LocaleController.new);

class LocaleController extends AsyncNotifier<Locale?> {
  static const _storageKey = 'app_locale';

  @override
  Future<Locale?> build() async {
    final prefs = await SharedPreferences.getInstance();
    final tag = prefs.getString(_storageKey);
    if (tag == null || tag == 'system') return null;
    return AppLocalizations.localeFromTag(tag);
  }

  Future<void> setLocale(Locale? locale) async {
    final prefs = await SharedPreferences.getInstance();
    if (locale == null) {
      await prefs.setString(_storageKey, 'system');
    } else {
      await prefs.setString(_storageKey, AppLocalizations.localeTag(locale));
    }
    state = AsyncData(locale);
  }
}

class SupportedAppLocale {
  const SupportedAppLocale({
    required this.locale,
    required this.nativeName,
    required this.englishName,
  });

  final Locale locale;
  final String nativeName;
  final String englishName;
}

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocaleItems = [
    SupportedAppLocale(
      locale: Locale('ko'),
      nativeName: '한국어',
      englishName: 'Korean',
    ),
    SupportedAppLocale(
      locale: Locale('en'),
      nativeName: 'English',
      englishName: 'English',
    ),
    SupportedAppLocale(
      locale: Locale('ja'),
      nativeName: '日本語',
      englishName: 'Japanese',
    ),
    SupportedAppLocale(
      locale: Locale.fromSubtags(languageCode: 'zh', countryCode: 'CN'),
      nativeName: '简体中文',
      englishName: 'Chinese (Simplified)',
    ),
    SupportedAppLocale(
      locale: Locale.fromSubtags(languageCode: 'zh', countryCode: 'TW'),
      nativeName: '繁體中文',
      englishName: 'Chinese (Traditional)',
    ),
    SupportedAppLocale(
      locale: Locale('es'),
      nativeName: 'Español',
      englishName: 'Spanish',
    ),
    SupportedAppLocale(
      locale: Locale('fr'),
      nativeName: 'Français',
      englishName: 'French',
    ),
    SupportedAppLocale(
      locale: Locale('de'),
      nativeName: 'Deutsch',
      englishName: 'German',
    ),
    SupportedAppLocale(
      locale: Locale('ar'),
      nativeName: 'العربية',
      englishName: 'Arabic',
    ),
    SupportedAppLocale(
      locale: Locale('pt'),
      nativeName: 'Português',
      englishName: 'Portuguese',
    ),
  ];

  static List<Locale> get supportedLocales =>
      supportedLocaleItems.map((item) => item.locale).toList(growable: false);

  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static Locale? localeFromTag(String tag) {
    final normalized = tag.replaceAll('_', '-').toLowerCase();
    for (final item in supportedLocaleItems) {
      if (localeTag(item.locale).toLowerCase() == normalized) {
        return item.locale;
      }
    }
    return null;
  }

  static String localeTag(Locale locale) {
    final countryCode = locale.countryCode;
    if (countryCode == null || countryCode.isEmpty) return locale.languageCode;
    return '${locale.languageCode}-$countryCode';
  }

  static Locale resolve(Locale? deviceLocale, Iterable<Locale> supported) {
    if (deviceLocale == null) return const Locale('en');

    for (final locale in supported) {
      if (locale.languageCode == deviceLocale.languageCode &&
          locale.countryCode == deviceLocale.countryCode) {
        return locale;
      }
    }
    for (final locale in supported) {
      if (locale.languageCode == deviceLocale.languageCode &&
          locale.countryCode == null) {
        return locale;
      }
    }
    if (deviceLocale.languageCode == 'zh') {
      return deviceLocale.scriptCode == 'Hant'
          ? const Locale.fromSubtags(languageCode: 'zh', countryCode: 'TW')
          : const Locale.fromSubtags(languageCode: 'zh', countryCode: 'CN');
    }
    return const Locale('en');
  }

  String get languageCode {
    if (locale.languageCode == 'zh') {
      return locale.countryCode == 'TW' ? 'zh-TW' : 'zh-CN';
    }
    return locale.languageCode;
  }

  bool get isRtl => locale.languageCode == 'ar';

  String t(String key, {Map<String, String> args = const {}}) {
    final table = _localizedValues[languageCode] ??
        _localizedValues[locale.languageCode] ??
        _localizedValues['en']!;
    var value = table[key];
    if (value == null && languageCode != 'en' && languageCode != 'ko') {
      final koSource = _localizedValues['ko']![key];
      if (koSource != null) value = _looseLocalizedFallback(koSource);
    }
    var resolved = value ?? _localizedValues['en']![key] ?? key;
    for (final entry in args.entries) {
      resolved = resolved.replaceAll('{${entry.key}}', entry.value);
    }
    return resolved;
  }

  String text(String source, {Map<String, String> args = const {}}) {
    if (languageCode == 'ko') {
      var value = source;
      for (final entry in args.entries) {
        value = value.replaceAll('{${entry.key}}', entry.value);
      }
      return value;
    }

    final ownTable =
        _rawTextValues[languageCode] ?? _rawTextValues[locale.languageCode];
    final value = ownTable?[source] ??
        (languageCode == 'en'
            ? (_rawTextValues['en']![source] ?? _looseEnglishFallback(source))
            : _looseLocalizedFallback(source));
    var resolved = value;
    for (final entry in args.entries) {
      resolved = resolved.replaceAll('{${entry.key}}', entry.value);
    }
    return resolved;
  }

  String _looseEnglishFallback(String source) {
    var value = source;
    for (final entry in _rawWordFallback.entries) {
      value = value.replaceAll(entry.key, entry.value);
    }
    return value;
  }

  String _looseLocalizedFallback(String source) {
    final wordTable = _rawWordFallbackByLanguage[languageCode] ??
        _rawWordFallbackByLanguage[locale.languageCode];
    if (wordTable == null) {
      return _rawTextValues['en']![source] ?? _looseEnglishFallback(source);
    }

    var value = source;
    final entries = wordTable.entries.toList()
      ..sort((a, b) => b.key.length.compareTo(a.key.length));
    for (final entry in entries) {
      value = value.replaceAll(entry.key, entry.value);
    }
    if (RegExp(r'[가-힣]').hasMatch(value)) {
      return _localizedEnglishFallback(source);
    }
    return value;
  }

  String _localizedEnglishFallback(String source) {
    var value = _rawTextValues['en']![source] ?? _looseEnglishFallback(source);
    final wordTable = _englishWordFallbackByLanguage[languageCode] ??
        _englishWordFallbackByLanguage[locale.languageCode];
    if (wordTable == null) return value;

    final entries = wordTable.entries.toList()
      ..sort((a, b) => b.key.length.compareTo(a.key.length));
    for (final entry in entries) {
      value = value.replaceAll(entry.key, entry.value);
    }
    return value;
  }
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String lt(String source, {Map<String, String> args = const {}}) =>
      l10n.text(source, args: args);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.any((supported) {
        return supported.languageCode == locale.languageCode;
      });

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const _localizedValues = <String, Map<String, String>>{
  'ko': {
    'app.name': '반려숨탄',
    'app.tagline': '반려동물 건강관리 앱',
    'nav.home': '홈',
    'nav.journal': '일지',
    'nav.notifications': '알림',
    'nav.profile': '프로필',
    'nav.settings': '설정',
    'nav.addAlarm': '알림 추가',
    'drawer.service': '서비스',
    'drawer.nearbyHospitals': '주변 병원 찾기',
    'drawer.nearbyHospitalsSub': '내 위치 기반 동물병원',
    'drawer.healthGuide': '건강관리 가이드',
    'drawer.healthGuideSub': '반려동물 건강 안내서',
    'drawer.app': '앱',
    'drawer.help': '도움말',
    'dialog.externalTitle': '외부 웹페이지로 이동해요',
    'dialog.externalHospitalBody':
        '주변 동물병원을 찾으려면\n외부 웹페이지가 필요해요.\n\n지금 바로 이동할까요?',
    'common.cancel': '취소',
    'common.go': '이동할게요',
    'common.delete': '삭제',
    'common.save': '저장하기',
    'common.loading': '준비 중...',
    'common.percent': '{percent}%',
    'toast.backToExit': '한 번 더 누르면 앱을 종료합니다',
    'toast.needPet': '아직 반려동물이 없네요. 프로필에서 먼저 등록해 주세요!',
    'settings.notifications': '알림',
    'settings.pushNotifications': '푸시 알림 허용',
    'settings.pushNotificationsSub': '기기 알림 권한 설정',
    'settings.languageSection': '언어',
    'settings.language': '앱 언어',
    'settings.languageSystem': '기기 설정 사용',
    'settings.languageChanged': '앱 언어가 변경됐어요',
    'settings.data': '데이터 관리',
    'settings.export': '데이터 내보내기',
    'settings.exportSub': 'ZIP 파일로 저장',
    'settings.import': '데이터 가져오기',
    'settings.importSub': 'ZIP 파일에서 복원',
    'settings.appInfo': '앱 정보',
    'settings.version': '앱 버전',
    'settings.privacy': '개인정보 처리방침',
    'settings.feedback': '피드백 보내기',
    'settings.feedbackSubject': '반려숨탄 피드백',
    'settings.emailAppMissing': '이메일 앱을 찾을 수 없어요',
    'settings.importConfirmBody':
        '기존의 모든 데이터가 삭제되고 백업 파일의 데이터로 교체됩니다.\n\n계속하시겠습니까?',
    'settings.importAction': '가져오기',
    'settings.importing': '데이터 가져오기',
    'settings.importSuccess': '백업 데이터를 복원했어요',
    'settings.importFailed': '가져오기에 실패했어요',
    'settings.exportTitle': '데이터 내보내기',
    'settings.exportBenefitTitle': '내 소중한 기록을 안전하게',
    'settings.exportBenefitPets': '모든 반려동물 프로필 & 사진',
    'settings.exportBenefitRecords': '건강 기록 · 일지 · 체중 전체',
    'settings.exportBenefitMedia': '첨부 이미지 & 영상 포함',
    'settings.storeUnavailable': '현재 스토어에 연결할 수 없어요.\n잠시 후 다시 시도해 주세요.',
    'settings.payAndExport': '{price} 결제하고 내보내기',
    'settings.unlocked': '잠금 해제됨',
    'settings.exportUnlockedBody':
        '모든 반려동물 정보와 기록을 ZIP 파일로 저장합니다.\n저장된 파일은 언제든 무료로 가져오기 복원할 수 있어요.',
    'settings.exporting': '내보내는 중...',
    'settings.exportZip': 'ZIP 파일로 내보내기',
    'settings.exportConfirmBody': '모든 반려동물 정보와 기록, 첨부 미디어를 ZIP 파일로 내보냅니다.',
    'settings.exportAction': '내보내기',
    'settings.exportSuccess': '백업 파일을 공유할 수 있어요',
    'settings.exportFailed': '내보내기에 실패했어요',
    'settings.purchaseFailed': '결제에 실패했어요',
    'error.dbInit': '앱 데이터를 준비하는 중 문제가 발생했습니다.\n잠시 후 다시 실행해 주세요.',
  },
  'en': {
    'app.name': 'Pet Sumtan',
    'app.tagline': 'Pet health care app',
    'nav.home': 'Home',
    'nav.journal': 'Journal',
    'nav.notifications': 'Alerts',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.addAlarm': 'Add alert',
    'drawer.service': 'Services',
    'drawer.nearbyHospitals': 'Find nearby hospitals',
    'drawer.nearbyHospitalsSub': 'Animal hospitals near you',
    'drawer.healthGuide': 'Health guide',
    'drawer.healthGuideSub': 'Pet health handbook',
    'drawer.app': 'App',
    'drawer.help': 'Help',
    'dialog.externalTitle': 'Open an external page',
    'dialog.externalHospitalBody':
        'Finding nearby animal hospitals requires an external web page.\n\nOpen it now?',
    'common.cancel': 'Cancel',
    'common.go': 'Go',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.loading': 'Preparing...',
    'common.percent': '{percent}%',
    'toast.backToExit': 'Press again to exit the app',
    'toast.needPet': 'No pet yet. Please add one from Profile first.',
    'settings.notifications': 'Notifications',
    'settings.pushNotifications': 'Allow push notifications',
    'settings.pushNotificationsSub': 'Device notification permission',
    'settings.languageSection': 'Language',
    'settings.language': 'App language',
    'settings.languageSystem': 'Use device settings',
    'settings.languageChanged': 'App language changed',
    'settings.data': 'Data management',
    'settings.export': 'Export data',
    'settings.exportSub': 'Save as a ZIP file',
    'settings.import': 'Import data',
    'settings.importSub': 'Restore from a ZIP file',
    'settings.appInfo': 'App info',
    'settings.version': 'App version',
    'settings.privacy': 'Privacy policy',
    'settings.feedback': 'Send feedback',
    'settings.feedbackSubject': 'Pet Sumtan feedback',
    'settings.emailAppMissing': 'No email app found',
    'settings.importConfirmBody':
        'All existing data will be deleted and replaced with the backup file.\n\nContinue?',
    'settings.importAction': 'Import',
    'settings.importing': 'Import data',
    'settings.importSuccess': 'Backup data restored',
    'settings.importFailed': 'Import failed',
    'settings.exportTitle': 'Export data',
    'settings.exportBenefitTitle': 'Keep your precious records safe',
    'settings.exportBenefitPets': 'All pet profiles and photos',
    'settings.exportBenefitRecords':
        'All health records, journals, and weights',
    'settings.exportBenefitMedia': 'Includes attached images and videos',
    'settings.storeUnavailable':
        'Cannot connect to the store right now.\nPlease try again later.',
    'settings.payAndExport': 'Pay {price} and export',
    'settings.unlocked': 'Unlocked',
    'settings.exportUnlockedBody':
        'Save all pet information and records as a ZIP file.\nYou can import and restore saved files for free anytime.',
    'settings.exporting': 'Exporting...',
    'settings.exportZip': 'Export as ZIP',
    'settings.exportConfirmBody':
        'Export all pet information, records, and attached media as a ZIP file.',
    'settings.exportAction': 'Export',
    'settings.exportSuccess': 'Backup file is ready to share',
    'settings.exportFailed': 'Export failed',
    'settings.purchaseFailed': 'Payment failed',
    'error.dbInit':
        'There was a problem preparing app data.\nPlease try again later.',
  },
  'ja': {
    'app.name': 'ペットスムタン',
    'app.tagline': 'ペット健康管理アプリ',
    'nav.home': 'ホーム',
    'nav.journal': '日誌',
    'nav.notifications': '通知',
    'nav.profile': 'プロフィール',
    'nav.settings': '設定',
    'nav.addAlarm': '通知を追加',
    'drawer.service': 'サービス',
    'drawer.nearbyHospitals': '近くの病院を探す',
    'drawer.nearbyHospitalsSub': '現在地周辺の動物病院',
    'drawer.healthGuide': '健康管理ガイド',
    'drawer.healthGuideSub': 'ペット健康ガイド',
    'drawer.app': 'アプリ',
    'drawer.help': 'ヘルプ',
    'dialog.externalTitle': '外部ページを開く',
    'dialog.externalHospitalBody': '近くの動物病院を探すには\n外部ウェブページが必要です。\n\n今すぐ移動しますか？',
    'common.cancel': 'キャンセル',
    'common.go': '移動する',
    'common.delete': '削除',
    'common.save': '保存する',
    'common.loading': '準備中...',
    'common.percent': '{percent}%',
    'toast.backToExit': 'もう一度押すとアプリを終了します',
    'toast.needPet': 'ペットがいません。プロフィールからまず登録してください！',
    'settings.notifications': '通知',
    'settings.pushNotifications': 'プッシュ通知を許可',
    'settings.pushNotificationsSub': '端末の通知権限設定',
    'settings.languageSection': '言語',
    'settings.language': 'アプリの言語',
    'settings.languageSystem': '端末の設定を使用',
    'settings.languageChanged': 'アプリの言語を変更しました',
    'settings.data': 'データ管理',
    'settings.export': 'データを書き出す',
    'settings.exportSub': 'ZIPファイルで保存',
    'settings.import': 'データを読み込む',
    'settings.importSub': 'ZIPファイルから復元',
    'settings.appInfo': 'アプリ情報',
    'settings.version': 'アプリバージョン',
    'settings.privacy': 'プライバシーポリシー',
    'settings.feedback': 'フィードバックを送信',
    'settings.feedbackSubject': 'ペットスムタン フィードバック',
    'settings.emailAppMissing': 'メールアプリが見つかりません',
    'settings.importConfirmBody':
        '既存のすべてのデータが削除され、バックアップファイルのデータに置き換えられます。\n\n続けますか？',
    'settings.importAction': '読み込む',
    'settings.importing': 'データを読み込み中',
    'settings.importSuccess': 'バックアップデータを復元しました',
    'settings.importFailed': '読み込みに失敗しました',
    'settings.exportTitle': 'データを書き出す',
    'settings.exportBenefitTitle': '大切な記録を安全に',
    'settings.exportBenefitPets': 'すべてのペットプロフィールと写真',
    'settings.exportBenefitRecords': '健康記録・日誌・体重すべて',
    'settings.exportBenefitMedia': '添付画像・動画を含む',
    'settings.storeUnavailable': '現在ストアに接続できません。\nしばらくしてからもう一度お試しください。',
    'settings.payAndExport': '{price}を支払って書き出す',
    'settings.unlocked': 'ロック解除済み',
    'settings.exportUnlockedBody':
        'すべてのペット情報と記録をZIPファイルで保存します。\n保存されたファイルはいつでも無料で読み込んで復元できます。',
    'settings.exporting': '書き出し中...',
    'settings.exportZip': 'ZIPファイルで書き出す',
    'settings.exportConfirmBody': 'すべてのペット情報、記録、添付メディアをZIPファイルで書き出します。',
    'settings.exportAction': '書き出す',
    'settings.exportSuccess': 'バックアップファイルを共有できます',
    'settings.exportFailed': '書き出しに失敗しました',
    'settings.purchaseFailed': '支払いに失敗しました',
    'error.dbInit': 'アプリデータの準備中に問題が発生しました。\nしばらくしてからもう一度起動してください。',
  },
  'zh-CN': {
    'app.name': '宠物 Sumtan',
    'app.tagline': '宠物健康管理应用',
    'nav.home': '首页',
    'nav.journal': '日记',
    'nav.notifications': '提醒',
    'nav.profile': '档案',
    'nav.settings': '设置',
    'nav.addAlarm': '添加提醒',
    'drawer.service': '服务',
    'drawer.nearbyHospitals': '查找附近医院',
    'drawer.nearbyHospitalsSub': '基于当前位置的动物医院',
    'drawer.healthGuide': '健康管理指南',
    'drawer.healthGuideSub': '宠物健康指南',
    'drawer.app': '应用',
    'drawer.help': '帮助',
    'dialog.externalTitle': '打开外部网页',
    'dialog.externalHospitalBody': '查找附近动物医院\n需要打开外部网页。\n\n现在跳转吗？',
    'common.cancel': '取消',
    'common.go': '前往',
    'common.delete': '删除',
    'common.save': '保存',
    'common.loading': '准备中...',
    'common.percent': '{percent}%',
    'toast.backToExit': '再按一次退出应用',
    'toast.needPet': '还没有宠物。请先在档案中注册！',
    'settings.notifications': '通知',
    'settings.pushNotifications': '允许推送通知',
    'settings.pushNotificationsSub': '设备通知权限设置',
    'settings.languageSection': '语言',
    'settings.language': '应用语言',
    'settings.languageSystem': '使用设备设置',
    'settings.languageChanged': '应用语言已更改',
    'settings.data': '数据管理',
    'settings.export': '导出数据',
    'settings.exportSub': '保存为 ZIP 文件',
    'settings.import': '导入数据',
    'settings.importSub': '从 ZIP 文件恢复',
    'settings.appInfo': '应用信息',
    'settings.version': '应用版本',
    'settings.privacy': '隐私政策',
    'settings.feedback': '发送反馈',
    'settings.feedbackSubject': '宠物 Sumtan 反馈',
    'settings.emailAppMissing': '找不到邮件应用',
    'settings.importConfirmBody': '所有现有数据将被删除并替换为备份文件中的数据。\n\n继续吗？',
    'settings.importAction': '导入',
    'settings.importing': '正在导入数据',
    'settings.importSuccess': '备份数据已恢复',
    'settings.importFailed': '导入失败',
    'settings.exportTitle': '导出数据',
    'settings.exportBenefitTitle': '安全保存珍贵记录',
    'settings.exportBenefitPets': '所有宠物档案和照片',
    'settings.exportBenefitRecords': '所有健康记录、日记和体重',
    'settings.exportBenefitMedia': '包含附件图片和视频',
    'settings.storeUnavailable': '当前无法连接到商店。\n请稍后再试。',
    'settings.payAndExport': '支付 {price} 并导出',
    'settings.unlocked': '已解锁',
    'settings.exportUnlockedBody': '将所有宠物信息和记录保存为 ZIP 文件。\n保存的文件随时可以免费导入恢复。',
    'settings.exporting': '正在导出...',
    'settings.exportZip': '导出为 ZIP',
    'settings.exportConfirmBody': '将所有宠物信息、记录和附件媒体导出为 ZIP 文件。',
    'settings.exportAction': '导出',
    'settings.exportSuccess': '备份文件已可分享',
    'settings.exportFailed': '导出失败',
    'settings.purchaseFailed': '支付失败',
    'error.dbInit': '准备应用数据时出现问题。\n请稍后再启动。',
  },
  'zh-TW': {
    'app.name': '寵物 Sumtan',
    'app.tagline': '寵物健康管理 App',
    'nav.home': '首頁',
    'nav.journal': '日誌',
    'nav.notifications': '提醒',
    'nav.profile': '檔案',
    'nav.settings': '設定',
    'nav.addAlarm': '新增提醒',
    'drawer.service': '服務',
    'drawer.nearbyHospitals': '尋找附近醫院',
    'drawer.nearbyHospitalsSub': '依目前位置尋找動物醫院',
    'drawer.healthGuide': '健康管理指南',
    'drawer.healthGuideSub': '寵物健康指南',
    'drawer.app': 'App',
    'drawer.help': '說明',
    'dialog.externalTitle': '開啟外部網頁',
    'dialog.externalHospitalBody': '尋找附近動物醫院\n需要開啟外部網頁。\n\n現在前往嗎？',
    'common.cancel': '取消',
    'common.go': '前往',
    'common.delete': '刪除',
    'common.save': '儲存',
    'common.loading': '準備中...',
    'common.percent': '{percent}%',
    'toast.backToExit': '再按一次即可關閉 App',
    'toast.needPet': '還沒有寵物。請先在檔案中登錄！',
    'settings.notifications': '通知',
    'settings.pushNotifications': '允許推播通知',
    'settings.pushNotificationsSub': '裝置通知權限設定',
    'settings.languageSection': '語言',
    'settings.language': 'App 語言',
    'settings.languageSystem': '使用裝置設定',
    'settings.languageChanged': 'App 語言已變更',
    'settings.data': '資料管理',
    'settings.export': '匯出資料',
    'settings.exportSub': '儲存為 ZIP 檔',
    'settings.import': '匯入資料',
    'settings.importSub': '從 ZIP 檔還原',
    'settings.appInfo': 'App 資訊',
    'settings.version': 'App 版本',
    'settings.privacy': '隱私權政策',
    'settings.feedback': '傳送意見回饋',
    'settings.feedbackSubject': '寵物 Sumtan 意見回饋',
    'settings.emailAppMissing': '找不到電子郵件 App',
    'settings.importConfirmBody': '所有現有資料將被刪除並替換為備份檔案的資料。\n\n確定繼續？',
    'settings.importAction': '匯入',
    'settings.importing': '正在匯入資料',
    'settings.importSuccess': '備份資料已還原',
    'settings.importFailed': '匯入失敗',
    'settings.exportTitle': '匯出資料',
    'settings.exportBenefitTitle': '安全保存珍貴記錄',
    'settings.exportBenefitPets': '所有寵物檔案和照片',
    'settings.exportBenefitRecords': '所有健康記錄、日誌和體重',
    'settings.exportBenefitMedia': '包含附件圖片和影片',
    'settings.storeUnavailable': '目前無法連線至 App Store。\n請稍後再試。',
    'settings.payAndExport': '支付 {price} 並匯出',
    'settings.unlocked': '已解鎖',
    'settings.exportUnlockedBody': '將所有寵物資訊和記錄儲存為 ZIP 檔。\n儲存的檔案隨時可以免費匯入還原。',
    'settings.exporting': '匯出中...',
    'settings.exportZip': '匯出為 ZIP 檔',
    'settings.exportConfirmBody': '將所有寵物資訊、記錄和附件媒體匯出為 ZIP 檔。',
    'settings.exportAction': '匯出',
    'settings.exportSuccess': '備份檔案已可分享',
    'settings.exportFailed': '匯出失敗',
    'settings.purchaseFailed': '付款失敗',
    'error.dbInit': '準備 App 資料時發生問題。\n請稍後再啟動。',
  },
  'es': {
    'app.name': 'Pet Sumtan',
    'app.tagline': 'App de salud para mascotas',
    'nav.home': 'Inicio',
    'nav.journal': 'Diario',
    'nav.notifications': 'Alertas',
    'nav.profile': 'Perfil',
    'nav.settings': 'Ajustes',
    'nav.addAlarm': 'Añadir alerta',
    'drawer.service': 'Servicios',
    'drawer.nearbyHospitals': 'Buscar clínicas cercanas',
    'drawer.nearbyHospitalsSub': 'Veterinarias cerca de ti',
    'drawer.healthGuide': 'Guía de salud',
    'drawer.healthGuideSub': 'Guía de salud para mascotas',
    'drawer.app': 'App',
    'drawer.help': 'Ayuda',
    'dialog.externalTitle': 'Abrir página externa',
    'dialog.externalHospitalBody':
        'Para encontrar veterinarias cercanas\nnecesitas abrir una página externa.\n\n¿Ir ahora?',
    'common.cancel': 'Cancelar',
    'common.go': 'Ir',
    'common.delete': 'Eliminar',
    'common.save': 'Guardar',
    'common.loading': 'Preparando...',
    'common.percent': '{percent}%',
    'toast.backToExit': 'Pulsa de nuevo para salir',
    'toast.needPet': 'Aún no tienes mascota. ¡Regístrala primero en Perfil!',
    'settings.notifications': 'Notificaciones',
    'settings.pushNotifications': 'Permitir notificaciones push',
    'settings.pushNotificationsSub':
        'Permiso de notificaciones del dispositivo',
    'settings.languageSection': 'Idioma',
    'settings.language': 'Idioma de la app',
    'settings.languageSystem': 'Usar ajustes del dispositivo',
    'settings.languageChanged': 'Idioma cambiado',
    'settings.data': 'Gestión de datos',
    'settings.export': 'Exportar datos',
    'settings.exportSub': 'Guardar como ZIP',
    'settings.import': 'Importar datos',
    'settings.importSub': 'Restaurar desde ZIP',
    'settings.appInfo': 'Información de la app',
    'settings.version': 'Versión de la app',
    'settings.privacy': 'Política de privacidad',
    'settings.feedback': 'Enviar comentarios',
    'settings.feedbackSubject': 'Pet Sumtan – Comentarios',
    'settings.emailAppMissing': 'No se encontró ninguna app de correo',
    'settings.importConfirmBody':
        'Todos los datos existentes se eliminarán y serán reemplazados por los del archivo de copia de seguridad.\n\n¿Continuar?',
    'settings.importAction': 'Importar',
    'settings.importing': 'Importando datos',
    'settings.importSuccess': 'Copia de seguridad restaurada',
    'settings.importFailed': 'Error al importar',
    'settings.exportTitle': 'Exportar datos',
    'settings.exportBenefitTitle': 'Guarda tus registros de forma segura',
    'settings.exportBenefitPets': 'Todos los perfiles y fotos de mascotas',
    'settings.exportBenefitRecords':
        'Todos los registros de salud, diarios y pesos',
    'settings.exportBenefitMedia': 'Incluye imágenes y videos adjuntos',
    'settings.storeUnavailable':
        'No se puede conectar a la tienda.\nVuelve a intentarlo más tarde.',
    'settings.payAndExport': 'Pagar {price} y exportar',
    'settings.unlocked': 'Desbloqueado',
    'settings.exportUnlockedBody':
        'Guarda toda la información y registros de mascotas como archivo ZIP.\nPuedes importar y restaurar el archivo gratis en cualquier momento.',
    'settings.exporting': 'Exportando...',
    'settings.exportZip': 'Exportar como ZIP',
    'settings.exportConfirmBody':
        'Exporta toda la información, registros y archivos adjuntos en un ZIP.',
    'settings.exportAction': 'Exportar',
    'settings.exportSuccess':
        'Archivo de copia de seguridad listo para compartir',
    'settings.exportFailed': 'Error al exportar',
    'settings.purchaseFailed': 'Error en el pago',
    'error.dbInit':
        'Hubo un problema al preparar los datos de la app.\nVuelve a intentarlo más tarde.',
  },
  'fr': {
    'app.name': 'Pet Sumtan',
    'app.tagline': 'App de santé pour animaux',
    'nav.home': 'Accueil',
    'nav.journal': 'Journal',
    'nav.notifications': 'Alertes',
    'nav.profile': 'Profil',
    'nav.settings': 'Réglages',
    'nav.addAlarm': 'Ajouter une alerte',
    'drawer.service': 'Services',
    'drawer.nearbyHospitals': 'Trouver des cliniques proches',
    'drawer.nearbyHospitalsSub': 'Cliniques vétérinaires près de vous',
    'drawer.healthGuide': 'Guide santé',
    'drawer.healthGuideSub': 'Guide santé pour animaux',
    'drawer.app': 'App',
    'drawer.help': 'Aide',
    'dialog.externalTitle': 'Ouvrir une page externe',
    'dialog.externalHospitalBody':
        'Trouver des cliniques vétérinaires\nnécessite une page web externe.\n\nOuvrir maintenant ?',
    'common.cancel': 'Annuler',
    'common.go': 'Ouvrir',
    'common.delete': 'Supprimer',
    'common.save': 'Enregistrer',
    'common.loading': 'Chargement...',
    'common.percent': '{percent} %',
    'toast.backToExit': 'Appuyez à nouveau pour quitter',
    'toast.needPet': 'Aucun animal enregistré. Ajoutez-en un depuis Profil !',
    'settings.notifications': 'Notifications',
    'settings.pushNotifications': 'Autoriser les notifications',
    'settings.pushNotificationsSub': 'Autorisations de notification',
    'settings.languageSection': 'Langue',
    'settings.language': "Langue de l'app",
    'settings.languageSystem': "Utiliser la langue de l'appareil",
    'settings.languageChanged': "Langue de l'app modifiée",
    'settings.data': 'Gestion des données',
    'settings.export': 'Exporter les données',
    'settings.exportSub': 'Enregistrer en ZIP',
    'settings.import': 'Importer les données',
    'settings.importSub': 'Restaurer depuis un ZIP',
    'settings.appInfo': "Infos de l'app",
    'settings.version': "Version de l'app",
    'settings.privacy': 'Politique de confidentialité',
    'settings.feedback': 'Envoyer un avis',
    'settings.feedbackSubject': 'Pet Sumtan – Avis',
    'settings.emailAppMissing': 'Aucune app e-mail trouvée',
    'settings.importConfirmBody':
        'Toutes les données existantes seront supprimées et remplacées par celles du fichier de sauvegarde.\n\nContinuer ?',
    'settings.importAction': 'Importer',
    'settings.importing': 'Importation en cours',
    'settings.importSuccess': 'Sauvegarde restaurée',
    'settings.importFailed': "Échec de l'importation",
    'settings.exportTitle': 'Exporter les données',
    'settings.exportBenefitTitle':
        'Gardez vos précieux enregistrements en sécurité',
    'settings.exportBenefitPets': "Tous les profils et photos d'animaux",
    'settings.exportBenefitRecords':
        'Tous les journaux, enregistrements et poids',
    'settings.exportBenefitMedia': 'Inclut les images et vidéos jointes',
    'settings.storeUnavailable':
        'Impossible de se connecter au Store.\nVeuillez réessayer plus tard.',
    'settings.payAndExport': 'Payer {price} et exporter',
    'settings.unlocked': 'Débloqué',
    'settings.exportUnlockedBody':
        'Enregistrez toutes les infos et données de vos animaux en ZIP.\nVous pouvez les importer et restaurer gratuitement à tout moment.',
    'settings.exporting': 'Exportation...',
    'settings.exportZip': 'Exporter en ZIP',
    'settings.exportConfirmBody':
        'Exporte toutes les infos, données et médias de vos animaux en ZIP.',
    'settings.exportAction': 'Exporter',
    'settings.exportSuccess': 'Fichier de sauvegarde prêt à partager',
    'settings.exportFailed': "Échec de l'exportation",
    'settings.purchaseFailed': 'Échec du paiement',
    'error.dbInit':
        'Un problème est survenu lors de la préparation des données.\nVeuillez réessayer plus tard.',
  },
  'de': {
    'app.name': 'Pet Sumtan',
    'app.tagline': 'App für Tiergesundheit',
    'nav.home': 'Start',
    'nav.journal': 'Tagebuch',
    'nav.notifications': 'Alarme',
    'nav.profile': 'Profil',
    'nav.settings': 'Einstellungen',
    'nav.addAlarm': 'Alarm hinzufügen',
    'drawer.service': 'Dienste',
    'drawer.nearbyHospitals': 'Kliniken in der Nähe finden',
    'drawer.nearbyHospitalsSub': 'Tierkliniken in Ihrer Nähe',
    'drawer.healthGuide': 'Gesundheitsratgeber',
    'drawer.healthGuideSub': 'Ratgeber für Tiergesundheit',
    'drawer.app': 'App',
    'drawer.help': 'Hilfe',
    'dialog.externalTitle': 'Externe Seite öffnen',
    'dialog.externalHospitalBody':
        'Um Tierkliniken in der Nähe zu finden,\nwird eine externe Webseite benötigt.\n\nJetzt öffnen?',
    'common.cancel': 'Abbrechen',
    'common.go': 'Öffnen',
    'common.delete': 'Löschen',
    'common.save': 'Speichern',
    'common.loading': 'Wird vorbereitet...',
    'common.percent': '{percent} %',
    'toast.backToExit': 'Nochmals drücken zum Beenden',
    'toast.needPet': 'Noch kein Haustier. Bitte zuerst im Profil hinzufügen!',
    'settings.notifications': 'Mitteilungen',
    'settings.pushNotifications': 'Push-Mitteilungen erlauben',
    'settings.pushNotificationsSub': 'Mitteilungsberechtigungen des Geräts',
    'settings.languageSection': 'Sprache',
    'settings.language': 'App-Sprache',
    'settings.languageSystem': 'Geräteeinstellungen verwenden',
    'settings.languageChanged': 'App-Sprache geändert',
    'settings.data': 'Datenverwaltung',
    'settings.export': 'Daten exportieren',
    'settings.exportSub': 'Als ZIP speichern',
    'settings.import': 'Daten importieren',
    'settings.importSub': 'Aus ZIP wiederherstellen',
    'settings.appInfo': 'App-Info',
    'settings.version': 'App-Version',
    'settings.privacy': 'Datenschutzerklärung',
    'settings.feedback': 'Feedback senden',
    'settings.feedbackSubject': 'Pet Sumtan – Feedback',
    'settings.emailAppMissing': 'Keine E-Mail-App gefunden',
    'settings.importConfirmBody':
        'Alle vorhandenen Daten werden gelöscht und durch die Sicherungsdaten ersetzt.\n\nFortfahren?',
    'settings.importAction': 'Importieren',
    'settings.importing': 'Daten werden importiert',
    'settings.importSuccess': 'Sicherung wiederhergestellt',
    'settings.importFailed': 'Import fehlgeschlagen',
    'settings.exportTitle': 'Daten exportieren',
    'settings.exportBenefitTitle': 'Deine Aufzeichnungen sicher aufbewahren',
    'settings.exportBenefitPets': 'Alle Tierprofile und Fotos',
    'settings.exportBenefitRecords':
        'Alle Gesundheitseinträge, Tagebücher und Gewichte',
    'settings.exportBenefitMedia': 'Inklusive angehängter Bilder und Videos',
    'settings.storeUnavailable':
        'Verbindung zum Store nicht möglich.\nBitte später erneut versuchen.',
    'settings.payAndExport': '{price} bezahlen und exportieren',
    'settings.unlocked': 'Entsperrt',
    'settings.exportUnlockedBody':
        'Alle Tierinfos und Einträge als ZIP speichern.\nDie Datei kann jederzeit kostenlos importiert und wiederhergestellt werden.',
    'settings.exporting': 'Wird exportiert...',
    'settings.exportZip': 'Als ZIP exportieren',
    'settings.exportConfirmBody':
        'Alle Tierinfos, Einträge und Medien werden als ZIP exportiert.',
    'settings.exportAction': 'Exportieren',
    'settings.exportSuccess': 'Sicherungsdatei kann geteilt werden',
    'settings.exportFailed': 'Export fehlgeschlagen',
    'settings.purchaseFailed': 'Zahlung fehlgeschlagen',
    'error.dbInit':
        'Beim Vorbereiten der App-Daten ist ein Problem aufgetreten.\nBitte später erneut starten.',
  },
  'ar': {
    'app.name': 'بت سمتان',
    'app.tagline': 'تطبيق رعاية صحة الحيوانات الأليفة',
    'nav.home': 'الرئيسية',
    'nav.journal': 'السجل',
    'nav.notifications': 'التنبيهات',
    'nav.profile': 'الملف',
    'nav.settings': 'الإعدادات',
    'nav.addAlarm': 'إضافة تنبيه',
    'drawer.service': 'الخدمات',
    'drawer.nearbyHospitals': 'البحث عن عيادات قريبة',
    'drawer.nearbyHospitalsSub': 'عيادات بيطرية قريبة من موقعك',
    'drawer.healthGuide': 'دليل الرعاية الصحية',
    'drawer.healthGuideSub': 'دليل صحة الحيوانات الأليفة',
    'drawer.app': 'التطبيق',
    'drawer.help': 'المساعدة',
    'dialog.externalTitle': 'فتح صفحة خارجية',
    'dialog.externalHospitalBody':
        'للعثور على عيادات بيطرية قريبة\nتحتاج إلى فتح صفحة ويب خارجية.\n\nالانتقال الآن؟',
    'common.cancel': 'إلغاء',
    'common.go': 'انتقال',
    'common.delete': 'حذف',
    'common.save': 'حفظ',
    'common.loading': 'جارٍ التحضير...',
    'common.percent': '{percent}%',
    'toast.backToExit': 'اضغط مرة أخرى للخروج',
    'toast.needPet':
        'لا يوجد حيوان أليف بعد. يُرجى التسجيل من ملفك الشخصي أولاً!',
    'settings.notifications': 'الإشعارات',
    'settings.pushNotifications': 'السماح بالإشعارات',
    'settings.pushNotificationsSub': 'أذونات إشعارات الجهاز',
    'settings.languageSection': 'اللغة',
    'settings.language': 'لغة التطبيق',
    'settings.languageSystem': 'استخدام إعدادات الجهاز',
    'settings.languageChanged': 'تم تغيير لغة التطبيق',
    'settings.data': 'إدارة البيانات',
    'settings.export': 'تصدير البيانات',
    'settings.exportSub': 'حفظ كملف ZIP',
    'settings.import': 'استيراد البيانات',
    'settings.importSub': 'استعادة من ملف ZIP',
    'settings.appInfo': 'معلومات التطبيق',
    'settings.version': 'إصدار التطبيق',
    'settings.privacy': 'سياسة الخصوصية',
    'settings.feedback': 'إرسال ملاحظات',
    'settings.feedbackSubject': 'ملاحظات Pet Sumtan',
    'settings.emailAppMissing': 'لم يتم العثور على تطبيق بريد إلكتروني',
    'settings.importConfirmBody':
        'سيتم حذف جميع البيانات الموجودة واستبدالها ببيانات ملف النسخ الاحتياطي.\n\nهل تريد المتابعة؟',
    'settings.importAction': 'استيراد',
    'settings.importing': 'جارٍ استيراد البيانات',
    'settings.importSuccess': 'تمت استعادة النسخة الاحتياطية',
    'settings.importFailed': 'فشل الاستيراد',
    'settings.exportTitle': 'تصدير البيانات',
    'settings.exportBenefitTitle': 'احتفظ بسجلاتك الثمينة بأمان',
    'settings.exportBenefitPets': 'جميع ملفات الحيوانات الأليفة والصور',
    'settings.exportBenefitRecords': 'جميع السجلات الصحية والمذكرات والأوزان',
    'settings.exportBenefitMedia': 'يشمل الصور ومقاطع الفيديو المرفقة',
    'settings.storeUnavailable':
        'تعذّر الاتصال بالمتجر حالياً.\nيُرجى المحاولة مرة أخرى لاحقاً.',
    'settings.payAndExport': 'دفع {price} وتصدير',
    'settings.unlocked': 'تم الفتح',
    'settings.exportUnlockedBody':
        'احفظ جميع معلومات وسجلات حيواناتك الأليفة في ملف ZIP.\nيمكنك استيراد الملف المحفوظ واستعادته مجاناً في أي وقت.',
    'settings.exporting': 'جارٍ التصدير...',
    'settings.exportZip': 'تصدير بصيغة ZIP',
    'settings.exportConfirmBody':
        'تصدير جميع المعلومات والسجلات وملفات الوسائط إلى ملف ZIP.',
    'settings.exportAction': 'تصدير',
    'settings.exportSuccess': 'ملف النسخ الاحتياطي جاهز للمشاركة',
    'settings.exportFailed': 'فشل التصدير',
    'settings.purchaseFailed': 'فشل الدفع',
    'error.dbInit':
        'حدثت مشكلة أثناء تحضير بيانات التطبيق.\nيُرجى إعادة التشغيل بعد قليل.',
  },
  'pt': {
    'app.name': 'Pet Sumtan',
    'app.tagline': 'App de saúde para pets',
    'nav.home': 'Início',
    'nav.journal': 'Diário',
    'nav.notifications': 'Alertas',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configurações',
    'nav.addAlarm': 'Adicionar alerta',
    'drawer.service': 'Serviços',
    'drawer.nearbyHospitals': 'Encontrar clínicas próximas',
    'drawer.nearbyHospitalsSub': 'Hospitais veterinários perto de você',
    'drawer.healthGuide': 'Guia de saúde',
    'drawer.healthGuideSub': 'Guia de saúde para pets',
    'drawer.app': 'App',
    'drawer.help': 'Ajuda',
    'dialog.externalTitle': 'Abrir página externa',
    'dialog.externalHospitalBody':
        'Para encontrar clínicas veterinárias próximas,\nserá necessário abrir uma página externa.\n\nAbrir agora?',
    'common.cancel': 'Cancelar',
    'common.go': 'Ir',
    'common.delete': 'Excluir',
    'common.save': 'Salvar',
    'common.loading': 'Preparando...',
    'common.percent': '{percent}%',
    'toast.backToExit': 'Pressione novamente para sair',
    'toast.needPet': 'Nenhum pet ainda. Cadastre um no Perfil primeiro!',
    'settings.notifications': 'Notificações',
    'settings.pushNotifications': 'Permitir notificações push',
    'settings.pushNotificationsSub': 'Permissão de notificações do dispositivo',
    'settings.languageSection': 'Idioma',
    'settings.language': 'Idioma do app',
    'settings.languageSystem': 'Usar configurações do dispositivo',
    'settings.languageChanged': 'Idioma do app alterado',
    'settings.data': 'Gerenciamento de dados',
    'settings.export': 'Exportar dados',
    'settings.exportSub': 'Salvar como ZIP',
    'settings.import': 'Importar dados',
    'settings.importSub': 'Restaurar de um ZIP',
    'settings.appInfo': 'Informações do app',
    'settings.version': 'Versão do app',
    'settings.privacy': 'Política de privacidade',
    'settings.feedback': 'Enviar feedback',
    'settings.feedbackSubject': 'Feedback – Pet Sumtan',
    'settings.emailAppMissing': 'Nenhum app de e-mail encontrado',
    'settings.importConfirmBody':
        'Todos os dados existentes serão excluídos e substituídos pelos dados do arquivo de backup.\n\nContinuar?',
    'settings.importAction': 'Importar',
    'settings.importing': 'Importando dados',
    'settings.importSuccess': 'Dados de backup restaurados',
    'settings.importFailed': 'Falha na importação',
    'settings.exportTitle': 'Exportar dados',
    'settings.exportBenefitTitle': 'Guarde seus registros com segurança',
    'settings.exportBenefitPets': 'Todos os perfis e fotos de pets',
    'settings.exportBenefitRecords':
        'Todos os registros de saúde, diários e pesos',
    'settings.exportBenefitMedia': 'Inclui imagens e vídeos anexados',
    'settings.storeUnavailable':
        'Não foi possível conectar à loja.\nTente novamente mais tarde.',
    'settings.payAndExport': 'Pagar {price} e exportar',
    'settings.unlocked': 'Desbloqueado',
    'settings.exportUnlockedBody':
        'Salve todas as informações e registros dos seus pets como um arquivo ZIP.\nVocê pode importar e restaurar o arquivo gratuitamente a qualquer momento.',
    'settings.exporting': 'Exportando...',
    'settings.exportZip': 'Exportar como ZIP',
    'settings.exportConfirmBody':
        'Exporta todas as informações, registros e mídias dos pets em um arquivo ZIP.',
    'settings.exportAction': 'Exportar',
    'settings.exportSuccess': 'Arquivo de backup pronto para compartilhar',
    'settings.exportFailed': 'Falha na exportação',
    'settings.purchaseFailed': 'Falha no pagamento',
    'error.dbInit':
        'Ocorreu um problema ao preparar os dados do app.\nTente novamente mais tarde.',
  },
};

const _rawTextValues = <String, Map<String, String>>{
  'en': {
    '도움말': 'Help',
    '건강관리 가이드': 'Health guide',
    '강아지': 'Dog',
    '고양이': 'Cat',
    '🐶 강아지': '🐶 Dog',
    '🐱 고양이': '🐱 Cat',
    '저장됐어요': 'Saved',
    '취소': 'Cancel',
    '삭제': 'Delete',
    '삭제하기': 'Delete',
    '저장하기': 'Save',
    '메모': 'Memo',
    '자유롭게 메모를 남겨보세요': 'Add a memo freely',
    '+ 추가': '+ Add',
    '오류가 발생했어요': 'An error occurred',
    '오류가 발생했어요\n{error}': 'An error occurred\n{error}',
    '반려동물': 'Pet',
    '반려동물 선택': 'Select pet',
    '새 반려동물 추가하기': 'Add a new pet',
    '등록된 알림이 없네요': 'No alerts yet',
    '{petName}는 오늘도 건강하게 지내봐요!\n아래 알림 추가 버튼을 눌러 시작해보세요.':
        'Keep {petName} healthy today.\nTap Add alert below to get started.',
    '예정된 알림': 'Scheduled alerts',
    '스와이프하면 삭제할 수 있어요': 'Swipe to delete',
    '알림 종류 선택': 'Select alert type',
    '병원 예약': 'Vet appointment',
    '투약': 'Medication',
    '식사 시간': 'Meal time',
    '일일 리마인더': 'Daily reminder',
    '알림': 'Alert',
    '예방접종 예정일을 확인해 주세요.': 'Please check the vaccination date.',
    '병원 예약 시간이 다가왔어요.': 'Your vet appointment is coming up.',
    '투약할 시간이에요.': 'It is time for medication.',
    '식사 시간을 챙겨 주세요.': 'Please remember meal time.',
    '오늘의 건강 기록을 남겨 주세요.': 'Please add today’s health record.',
    '반려동물 건강관리 알림입니다.': 'Pet health care alert.',
    '알림이 삭제됐어요 🗑️': 'Alert deleted',
    '지난 알림 숨기기': 'Hide past alerts',
    '지난 알림 보기': 'Show past alerts',
    '전체 삭제': 'Delete all',
    '지난 알림 삭제': 'Delete past alerts',
    '지난 알림 {count}개를 모두 삭제할까요?': 'Delete all {count} past alerts?',
    '지난 알림이 모두 삭제됐어요': 'All past alerts deleted',
    '지남': 'Past',
    '오늘': 'Today',
    '내일 같은 시간': 'Tomorrow, same time',
    '언제 다시 알려드릴까요?': 'When should we remind you again?',
    '5분 뒤': 'In 5 minutes',
    '10분 뒤': 'In 10 minutes',
    '30분 뒤': 'In 30 minutes',
    '1시간 뒤': 'In 1 hour',
    '3시간 뒤': 'In 3 hours',
    '직접 지정': 'Choose manually',
    '이 시간에 다시 알림': 'Remind me at this time',
    '🕐 {time}에 다시 알려드릴게요': 'We will remind you at {time}',
    '지금 이후의 시간을 선택해주세요': 'Please choose a future time',
    '기록 → {typeLabel} 항목에서 확인할 수 있어요':
        'You can check it under Record > {typeLabel}.',
    '예정된 푸시 알림도 함께 취소돼요.':
        'The scheduled push notification will also be canceled.',
    '재예약하기': 'Reschedule',
    '이 알림 삭제하기': 'Delete this alert',
    '백신 이름 *': 'Vaccine name *',
    '예) 광견병, 종합백신 등': 'e.g. Rabies, combo vaccine',
    '예정일 *': 'Date *',
    '알림 시점': 'Reminder timing',
    '당일': 'Same day',
    '알림 시각 *': 'Reminder time *',
    '메모를 입력하세요': 'Enter a memo',
    '방문 목적 *': 'Visit purpose *',
    '예) 정기검진, 피부 진료 등': 'e.g. Checkup, skin treatment',
    '예약 일시 *': 'Appointment date and time *',
    '병원명': 'Hospital name',
    '병원 이름을 입력하세요': 'Enter hospital name',
    '약품 이름 *': 'Medicine name *',
    '예) 심장사상충, 구충제 등': 'e.g. Heartworm, dewormer',
    '반복 *': 'Repeat *',
    '없음': 'None',
    '매일': 'Daily',
    '매주': 'Weekly',
    '매달': 'Monthly',
    '평일': 'Weekdays',
    '평일만': 'Weekdays only',
    '주말': 'Weekends',
    '주말만': 'Weekends only',
    '투약 일시 *': 'Medication date and time *',
    '투약 시각 *': 'Medication time *',
    '알림 이름 *': 'Alert name *',
    '예) 아침 식사, 저녁 밥 등': 'e.g. Breakfast, dinner',
    '식사 시각 *': 'Meal time *',
    '알림 문구': 'Alert message',
    '예) 콩이 오늘 기록 남기셨나요? 🐾': 'e.g. Did you add today’s record?',
    '이 알림의 예정일이 지났어요.\n새 날짜로 변경하거나 삭제할 수 있어요.':
        'This alert date has passed.\nYou can choose a new date or delete it.',
    '날짜 재선택': 'Select date again',
    '날짜 선택': 'Select date',
    '시각 선택': 'Select time',
    '오늘의 상태': 'Today’s status',
    '+ 기록하기': '+ Add record',
    '오늘의 리마인더': 'Today’s reminders',
    '오늘의 기록': 'Today’s records',
    '전체 보기': 'View all',
    '이번 주 통계': 'This week’s stats',
    '배변 횟수': 'Potty count',
    '식사 횟수': 'Meal count',
    '음수 단계': 'Water level',
    '회': 'times',
    '끼': 'meals',
    '점': 'pts',
    '기록이 삭제됐어요 🗑️': 'Record deleted',
    '기록이 수정됐어요': 'Record updated',
    '기록을 삭제할까요?': 'Delete this record?',
    '이 기록 삭제하기': 'Delete this record',
    '유형': 'Type',
    '상태': 'Status',
    '컨디션 점수': 'Condition score',
    '증상 태그': 'Symptom tags',
    '약품명': 'Medicine name',
    '용량': 'Dose',
    '투약 방법': 'Medication method',
    '체중 (kg)': 'Weight (kg)',
    '측정 방법': 'Measurement method',
    '식사 종류': 'Meal type',
    '식사량': 'Meal amount',
    '급여량': 'Serving amount',
    '음수량': 'Water amount',
    '진료 유형': 'Visit type',
    '진단명': 'Diagnosis',
    '백신 종류': 'Vaccine type',
    '부작용': 'Side effects',
    '미용 종류': 'Grooming type',
    '샵 이름': 'Shop name',
    '비용': 'Cost',
    '다음 예약일': 'Next appointment',
    '빗질 부위': 'Brushing area',
    '소요 시간': 'Duration',
    '산책 시간': 'Walk time',
    '거리': 'Distance',
    '제목': 'Title',
    '중요도': 'Priority',
    '대변': 'Stool',
    '소변': 'Urine',
    '구토': 'Vomiting',
    '정상': 'Normal',
    '묽음': 'Loose',
    '딱딱함': 'Hard',
    '혈변': 'Blood in stool',
    '기침': 'Cough',
    '무기력': 'Lethargy',
    '식욕부진': 'Loss of appetite',
    '설사': 'Diarrhea',
    '콧물': 'Runny nose',
    '재채기': 'Sneezing',
    '떨림': 'Trembling',
    '혈뇨': 'Blood in urine',
    '경구': 'Oral',
    '주사': 'Injection',
    '외용': 'Topical',
    '점안': 'Eye drops',
    '점이': 'Ear drops',
    '동물병원': 'Vet hospital',
    '가정용 체중계': 'Home scale',
    '안고 측정': 'Hold and weigh',
    '아침': 'Breakfast',
    '점심': 'Lunch',
    '저녁': 'Dinner',
    '간식': 'Snack',
    '매우 적음': 'Very little',
    '적음': 'Little',
    '보통': 'Normal',
    '많음': 'Much',
    '매우 많음': 'Very much',
    '일반': 'Normal',
    '정기검진': 'Checkup',
    '응급': 'Emergency',
    '경미': 'Mild',
    '심각': 'Severe',
    '목욕': 'Bath',
    '전체미용': 'Full grooming',
    '부분미용': 'Partial grooming',
    '발톱': 'Nails',
    '귀청소': 'Ear cleaning',
    '치석제거': 'Tartar removal',
    '항문낭': 'Anal glands',
    '전체': 'All',
    '등': 'Back',
    '배': 'Belly',
    '꼬리': 'Tail',
    '얼굴': 'Face',
    '발': 'Paws',
    '중요': 'Important',
    '사진 · 동영상': 'Photos · Videos',
    '미디어 추가': 'Add media',
    '미디어 추가 방법 선택': 'Choose how to add media',
    '카메라로 촬영': 'Use camera',
    '사진 또는 동영상 촬영': 'Take a photo or video',
    '갤러리에서 선택': 'Choose from gallery',
    '사진 · 동영상 다중 선택 가능': 'Select multiple photos and videos',
    '사진 촬영': 'Take photo',
    '카메라로 사진을 촬영': 'Take a photo with camera',
    '동영상 촬영': 'Record video',
    '카메라로 동영상을 촬영': 'Record a video with camera',
    '이 사진 삭제': 'Delete this photo',
    '사진을 삭제할까요?': 'Delete this photo?',
    '이 동영상 삭제': 'Delete this video',
    '동영상을 삭제할까요?': 'Delete this video?',
    '음소거': 'Muted',
    '소리 켜짐': 'Sound on',
    '설정에서 권한을 허용해 주세요': 'Please allow permission in Settings',
    '설정 열기': 'Open settings',
    '개인정보 처리방침': 'Privacy policy',
    '개발자에게 문의하기': 'Contact the developer',
    '문의': 'Contact',
    '설정': 'Settings',
    '데이터 내보내기': 'Export data',
    '데이터 가져오기': 'Import data',
    '피드백 보내기': 'Send feedback',
    '자주 묻는 질문': 'FAQ',
    '홈 화면': 'Home screen',
    '일지 화면': 'Journal screen',
    '알림 화면': 'Alerts screen',
    '반려동물 관리': 'Pet management',
    '기록 카테고리': 'Record categories',
    '반려숨탄이란?': 'What is Pet Sumtan?',
    '오늘의 기록 요약': 'Today’s record summary',
    '주간 통계': 'Weekly stats',
    '체중 변화 그래프': 'Weight change chart',
    '주변 병원 찾기': 'Find nearby hospitals',
    '새 기록 추가 (+)': 'Add new record (+)',
    '기록 목록 보기': 'View records',
    '기록 수정 및 삭제': 'Edit and delete records',
    '사진·영상 첨부': 'Attach photos/videos',
    '알림 추가': 'Add alert',
    '반복 알림': 'Repeating alerts',
    '사전 알림 (D-7, D-3, D-1)': 'Advance alerts (D-7, D-3, D-1)',
    '알림 완료 처리': 'Complete alerts',
    '알림 삭제': 'Delete alerts',
    '반려동물 등록': 'Add a pet',
    '프로필 수정': 'Edit profile',
    '여러 마리 관리': 'Manage multiple pets',
    '강아지 건강 가이드': 'Dog health guide',
    '고양이 건강 가이드': 'Cat health guide',
    '알림 설정': 'Notification settings',
    '강아지 건강관리 가이드': 'Dog health care guide',
    '고양이 건강관리 가이드': 'Cat health care guide',
    '수의사 권장 기준을 바탕으로\n작성된 전문 건강 안내서예요.':
        'A professional health guide\nbased on veterinary recommendations.',
    '예방접종': 'Vaccination',
    '핵심 필수 접종 (Core Vaccine)': 'Core vaccines',
    '필수': 'Required',
    '선택 접종 (Non-Core)': 'Non-core vaccines',
    '권장': 'Recommended',
    '기생충 예방': 'Parasite prevention',
    '심장사상충': 'Heartworm',
    '매월': 'Monthly',
    '외부기생충 (벼룩·진드기)': 'External parasites (fleas/ticks)',
    '내부기생충': 'Internal parasites',
    '3~6개월': '3-6 months',
    '영양 관리': 'Nutrition',
    '치아 관리': 'Dental care',
    '건강검진': 'Health checkups',
    '응급 신호': 'Emergency signs',
    '나이': 'Age',
    '검진 주기': 'Checkup cycle',
    '주요 항목': 'Main items',
    '운동량': 'Exercise level',
    '해당 품종 예시': 'Breed examples',
    '낮음': 'Low',
    '높음': 'High',
    '메뉴': 'Menu',
    '안녕하세요! ': 'Hello! ',
    '\n오늘도 건강한가요? 🐾': '\nFeeling healthy today?',
    '아직 기록이 없어요': 'No records yet',
    '마지막 기록 · {time}': 'Last record · {time}',
    '평균 {value}{unit}/일': 'Avg {value}{unit}/day',
    '⚖️ 체중 추이': '⚖️ Weight trend',
    '⚖️ 체중 변화': '⚖️ Weight change',
    '체중 데이터가 없어요': 'No weight data yet',
    '실측 체중': 'Measured weight',
    '표준 범위': 'Standard range',
    '아직 오늘의 기록이 없어요': 'No records for today yet',
    '반려동물의 컨디션, 배변, 체중을\n기록해 건강을 관리해 보세요!':
        'Track condition, potty, and weight\nto care for your pet’s health.',
    '{date}의 기록이 없어요': 'No records for {date}',
    '{date} 기록 ({count}건)': '{date} records ({count})',
    '일': 'Sun',
    '월': 'Mon',
    '화': 'Tue',
    '수': 'Wed',
    '목': 'Thu',
    '금': 'Fri',
    '토': 'Sat',
    '📝 무엇을 기록할까요?': '📝 What would you like to record?',
    '저장 중 오류가 발생했어요: {error}': 'An error occurred while saving: {error}',
    '✅ 알림이 수정됐어요': 'Alert updated',
    '🔔 알림이 추가됐어요': 'Alert added',
    '알림 수정': 'Edit alert',
    '알림을 삭제할까요?': 'Delete this alert?',
    '{name}이 삭제되고\n예정된 푸시 알림도 함께 취소돼요.':
        '{name} will be deleted,\nand its scheduled push notification will be canceled.',
    '✅ 완료했어요': '✅ Done',
    '🕐 나중에': '🕐 Later',
    '✅ 완료 저장': '✅ Save completion',
    '{type}을 완료했나요?': 'Did you complete {type}?',
    '{name} 을(를)\n오늘 기록에 자동으로 저장할게요.':
        'We will automatically save\n{name} to today’s records.',
    '{name} 완료가 기록됐어요 ✅': '{name} completion saved',
    '👆 원하는 알림 종류를 탭하세요': '👆 Tap the alert type you want',
    '{count}개': '{count}',
    '{date} · 완료됨': '{date} · Completed',
    '⚠️ {date} 지남 · 탭해서 재예약': '⚠️ {date} past · Tap to reschedule',
    '완료됨': 'Completed',
    '수정': 'Edit',
    '{category} 기록이 삭제되고\n되돌릴 수 없어요.':
        '{category} record will be deleted\nand cannot be restored.',
    '💡 약품명과 용량을 입력해 주세요': 'Please enter medicine name and dose',
    '💡 약품명을 입력해 주세요': 'Please enter a medicine name',
    '💡 용량을 입력해 주세요': 'Please enter a dose',
    '💡 체중을 숫자로 입력해 주세요': 'Please enter weight as a number',
    '💡 체중을 입력해 주세요': 'Please enter weight',
    '💡 체중은 숫자로 입력해 주세요': 'Please enter weight as a number',
    '💡 산책 시간을 입력해 주세요': 'Please enter walk time',
    '💡 산책 시간은 숫자로 입력해 주세요': 'Please enter walk time as a number',
    '💡 산책 시간을 숫자로 입력해 주세요': 'Please enter walk time as a number',
    '💡 빗질 부위를 하나 이상 선택해 주세요': 'Please select at least one brushing area',
    '💡 백신 종류를 하나 이상 선택해 주세요': 'Please select at least one vaccine type',
    '💡 미용 종류를 하나 이상 선택해 주세요': 'Please select at least one grooming type',
    '💡 제목을 입력해 주세요': 'Please enter a title',
    '💡 백신 이름을 입력해 주세요': 'Please enter a vaccine name',
    '💡 예정일을 선택해 주세요': 'Please select a date',
    '💡 예정 시각을 선택해 주세요': 'Please select a time',
    '💡 방문 목적을 입력해 주세요': 'Please enter the visit purpose',
    '💡 예약 날짜를 선택해 주세요': 'Please select an appointment date',
    '💡 예약 시각을 선택해 주세요': 'Please select an appointment time',
    '💡 약품 이름을 입력해 주세요': 'Please enter a medicine name',
    '💡 투약 날짜를 선택해 주세요': 'Please select a medication date',
    '💡 투약 시각을 선택해 주세요': 'Please select a medication time',
    '💡 알림 이름을 입력해 주세요': 'Please enter an alert name',
    '💡 식사 시각을 선택해 주세요': 'Please select a meal time',
    '💡 알림 시각을 선택해 주세요': 'Please select an alert time',
    '아직 반려동물이 없네요 🐾 프로필에서 먼저 등록해 주세요!':
        'No pet yet. Please add one from Profile first.',
    '🔄 알림이 재예약됐어요': 'Alert rescheduled',
    '예: 콩이': 'e.g. Kong',
    '예: 말티즈': 'e.g. Maltese',
    '예: 말티즈, 페르시안': 'e.g. Maltese, Persian',
    '예: 30': 'e.g. 30',
    '예: 80': 'e.g. 80',
    '예: 200': 'e.g. 200',
    '예: 2.5': 'e.g. 2.5',
    '예: 35000': 'e.g. 35000',
    '예: 50000': 'e.g. 50000',
    '이름을 입력해 주세요': 'Please enter a name',
    '새 반려동물 추가': 'Add new pet',
    '기본 정보': 'Basic info',
    '식별 정보': 'Identification info',
    '식별 정보 (선택)': 'Identification info (optional)',
    '이름': 'Name',
    '종류': 'Type',
    '품종': 'Breed',
    '체중': 'Weight',
    '마이크로칩': 'Microchip',
    '등록번호': 'Registration number',
    '생년월일': 'Birth date',
    '성별': 'Gender',
    '수컷': 'Male',
    '암컷': 'Female',
    '수컷 ♂': 'Male ♂',
    '암컷 ♀': 'Female ♀',
    '중성화': 'Neutered',
    '완료': 'Done',
    '미완료': 'Not done',
    '미입력': 'Not entered',
    '미등록': 'Not registered',
    '강아지 🐶': 'Dog 🐶',
    '고양이 🐱': 'Cat 🐱',
    '기타 🐾': 'Other 🐾',
    '등록된 반려동물이 없어요': 'No pets registered',
    '반려동물을 등록하고\n건강을 함께 관리해봐요!': 'Add a pet and\nmanage health together.',
    '반려동물 등록하기': 'Add pet',
    '반려동물 편집': 'Edit pet',
    '중성화 여부': 'Neutering status',
    '중성화 완료': 'Neutered',
    '중성화 안 함': 'Not neutered',
    '날짜를 선택하세요': 'Select a date',
    '수정 완료': 'Save changes',
    '등록하기': 'Register',
    '{name} 삭제하기': 'Delete {name}',
    '{name}을(를) 삭제할까요?': 'Delete {name}?',
    '{name}의 모든 기록과 알림이 함께 삭제되며 복구할 수 없어요.':
        'All records and alerts for {name} will be deleted and cannot be restored.',
    '{name}이(가) 삭제됐어요': '{name} deleted',
    '{name}이(가) 추가됐어요 🐾': '{name} added',
    '지금은 스토어에 연결할 수 없어요. 잠시 후 다시 시도해 주세요.':
        'Cannot connect to the store right now. Please try again later.',
    '결제 정보를 확인 중이에요. 잠시 후 다시 눌러 주세요.':
        'Checking payment info. Please try again shortly.',
    '결제가 완료됐어요. 이제 새 친구 정보를 입력해 주세요.':
        'Payment complete. Please enter your new pet’s info.',
    '새 가족을 추가할까요?': 'Add a new family member?',
    '첫 번째 반려동물은 무료로 등록할 수 있고, 두 번째 가족부터는 한 가족당 결제가 필요해요.':
        'The first pet is free. From the second pet, each additional pet requires payment.',
    '현재 등록된 반려동물 {count}마리\n스토어 연결이 가능할 때 다시 시도해 주세요.':
        '{count} pets registered\nPlease try again when the store is available.',
    '현재 등록된 반려동물 {count}마리\n{price} 결제 후 새 가족을 추가할 수 있어요.':
        '{count} pets registered\nPay {price} to add a new family member.',
    '다음에 할게요': 'Maybe later',
    '연결 불가': 'Unavailable',
    '{price} 결제하고 추가': 'Pay {price} and add',
    '+ 다음 예약일 추가': '+ Add next appointment',
    '💩 배변이 기록됐어요': 'Potty record saved',
    '💗 컨디션이 기록됐어요': 'Condition record saved',
    '💊 투약이 기록됐어요': 'Medication record saved',
    '⚖️ 체중이 기록됐어요': 'Weight record saved',
    '🍽️ 식사가 기록됐어요': 'Meal record saved',
    '💧 음수가 기록됐어요': 'Water record saved',
    '🏥 병원 방문이 기록됐어요': 'Vet visit record saved',
    '💉 예방접종이 기록됐어요': 'Vaccination record saved',
    '✂️ 미용이 기록됐어요': 'Grooming record saved',
    '🪥 빗질이 기록됐어요': 'Brushing record saved',
    '🦮 산책이 기록됐어요': 'Walk record saved',
    '📝 메모가 기록됐어요': 'Memo saved',
    '더 궁금한 점이 있으신가요?': 'Have more questions?',
    '설정 > 피드백 보내기를 통해 문의해 주세요.\n빠르게 답변 드릴게요 🐾':
        'Contact us from Settings > Send feedback.\nWe will get back to you soon.',
    '설정 화면의 [피드백 보내기] 버튼을 통해 문의하시면\n빠르게 답변드리겠습니다.':
        'Contact us through Send feedback in Settings.\nWe will reply quickly.',
    '본 개인정보 처리방침은 2026년 1월 1일부터 시행됩니다.\n최종 수정일: 2026년 5월 8일':
        'This privacy policy is effective from January 1, 2026.\nLast updated: May 8, 2026',
    '수집된 정보는 아래 목적으로만 사용됩니다.':
        'Collected information is used only for the purposes below.',
    '반려숨탄은 데이터 내보내기(백업) 및 가져오기(복원) 기능을 제공합니다.':
        'Pet Sumtan provides data export (backup) and import (restore) features.',
    '본 개인정보 처리방침은 법령 또는 서비스 변경에 따라 업데이트될 수 있습니다.':
        'This privacy policy may be updated due to legal or service changes.',
    '개인정보 처리방침에 관한 문의사항은 아래 방법으로 연락해 주세요.':
        'For questions about this privacy policy, please contact us below.',
  },
};

const _rawWordFallbackByLanguage = <String, Map<String, String>>{
  'ja': {
    '반려숨탄': 'ペットスムタン',
    '반려동물 건강관리 앱': 'ペット健康管理アプリ',
    '반려동물 건강 안내서': 'ペット健康ガイド',
    '내 위치 기반 동물병원': '現在地周辺の動物病院',
    '주변 동물병원': '近くの動物病院',
    '주변 병원 찾기': '近くの病院を探す',
    '건강관리 가이드': '健康管理ガイド',
    '개인정보 처리방침': 'プライバシーポリシー',
    '데이터 관리': 'データ管理',
    '데이터 내보내기': 'データを書き出す',
    '데이터 가져오기': 'データを読み込む',
    '피드백 보내기': 'フィードバックを送信',
    '푸시 알림 허용': 'プッシュ通知を許可',
    '기기 알림 권한 설정': '端末の通知権限設定',
    '기기 설정 사용': '端末設定を使用',
    '앱 언어': 'アプリの言語',
    '앱 정보': 'アプリ情報',
    '앱 버전': 'アプリバージョン',
    'ZIP 파일로 저장': 'ZIPファイルで保存',
    'ZIP 파일에서 복원': 'ZIPファイルから復元',
    '이메일 앱을 찾을 수 없어요': 'メールアプリが見つかりません',
    '반려동물': 'ペット',
    '강아지': '犬',
    '고양이': '猫',
    '건강관리': '健康管理',
    '가이드': 'ガイド',
    '홈': 'ホーム',
    '일지': '日誌',
    '알림': '通知',
    '프로필': 'プロフィール',
    '설정': '設定',
    '서비스': 'サービス',
    '도움말': 'ヘルプ',
    '언어': '言語',
    '취소': 'キャンセル',
    '삭제': '削除',
    '저장하기': '保存',
    '저장': '保存',
    '추가': '追加',
    '선택': '選択',
    '확인': '確認',
    '기록': '記録',
    '예방접종': '予防接種',
    '병원 예약': '病院予約',
    '병원': '病院',
    '투약': '投薬',
    '식사 시간': '食事時間',
    '식사': '食事',
    '일일 리마인더': '毎日のリマインダー',
    '리마인더': 'リマインダー',
    '배변': '排泄',
    '컨디션': '体調',
    '체중': '体重',
    '음수': '飲水',
    '접종': '接種',
    '미용': 'グルーミング',
    '빗질': 'ブラッシング',
    '산책': '散歩',
    '메모': 'メモ',
    '사진': '写真',
    '동영상': '動画',
    '미디어': 'メディア',
    '카메라': 'カメラ',
    '갤러리': 'ギャラリー',
    '오늘': '今日',
    '이번 주': '今週',
    '전체': 'すべて',
    '필수': '必須',
    '권장': '推奨',
    '매월': '毎月',
    '없음': 'なし',
    '보통': '普通',
    '완료': '完了',
    '미완료': '未完了',
    '미입력': '未入力',
    '미등록': '未登録',
    '이름': '名前',
    '종류': '種類',
    '품종': '品種',
    '나이': '年齢',
    '성별': '性別',
    '수컷': 'オス',
    '암컷': 'メス',
    '중성화': '避妊・去勢',
    '기본 정보': '基本情報',
    '식별 정보': '識別情報',
    '마이크로칩': 'マイクロチップ',
    '등록번호': '登録番号',
    '생년월일': '生年月日',
    '비용': '費用',
    '제목': 'タイトル',
    '중요도': '重要度',
    '일반': '通常',
    '중요': '重要',
    '핵심 필수 접종': 'コアワクチン',
    '선택 접종': '任意ワクチン',
    '종합백신': '混合ワクチン',
    '광견병': '狂犬病',
    '코로나 장염': 'コロナ腸炎',
    '켄넬코프': 'ケンネルコフ',
    '인플루엔자': 'インフルエンザ',
    '기생충 예방': '寄生虫予防',
    '심장사상충': 'フィラリア',
    '외부기생충': '外部寄生虫',
    '내부기생충': '内部寄生虫',
    '정기 건강검진': '定期健康診断',
    '치아 & 구강 관리': '歯と口腔ケア',
    '절대 금지 음식': '絶対に与えてはいけない食べ物',
    '즉시 병원 방문이 필요한 증상': 'すぐに病院へ行くべき症状',
    '운동 & 정신 건강': '運動とメンタルヘルス',
    '품종별 권장 운동량': '犬種別の推奨運動量',
    '놀이 & 두뇌 자극': '遊びと知的刺激',
    '스트레스 신호 알아채기': 'ストレスサインに気づく',
    '사회화 & 환경 자극': '社会化と環境刺激',
    '고양이 주요 질환 주의': '猫の主な病気に注意',
    '수분 섭취 & 식이 관리': '水分摂取と食事管理',
    '환경 & 정신 건강': '環境とメンタルヘルス',
    '실내 환경 관리': '室内環境管理',
    '스트레스 관리': 'ストレス管理',
    '수의사 권장 기준': '獣医師推奨基準',
    '전문 건강 안내서': '専門的な健康ガイド',
    '생후': '生後',
    '매년': '毎年',
    '추가접종': '追加接種',
    '법정 의무접종': '法定義務接種',
    '예방약': '予防薬',
    '투여': '投与',
    '구충제': '駆虫薬',
    '검사': '検査',
    '증상': '症状',
    '정기 검진': '定期健診',
    '식욕': '食欲',
    '구토': '嘔吐',
    '설사': '下痢',
    '소변': '尿',
    '혈뇨': '血尿',
    '경련': 'けいれん',
    '발작': '発作',
    '출혈': '出血',
    '반려동물 전용 치약': 'ペット専用歯磨き粉',
    '동물병원': '動物病院',
    '벼룩': 'ノミ',
    '진드기': 'マダニ',
    '수의사': '獣医師',
    '주의': '注意',
    '정기': '定期',
    '매일': '毎日',
  },
  'zh-CN': {
    '반려숨탄': '宠物 Sumtan',
    '반려동물 건강관리 앱': '宠物健康管理应用',
    '반려동물 건강 안내서': '宠物健康指南',
    '내 위치 기반 동물병원': '基于当前位置的动物医院',
    '주변 동물병원': '附近动物医院',
    '주변 병원 찾기': '查找附近医院',
    '건강관리 가이드': '健康管理指南',
    '개인정보 처리방침': '隐私政策',
    '데이터 관리': '数据管理',
    '데이터 내보내기': '导出数据',
    '데이터 가져오기': '导入数据',
    '피드백 보내기': '发送反馈',
    '푸시 알림 허용': '允许推送通知',
    '기기 알림 권한 설정': '设备通知权限设置',
    '기기 설정 사용': '使用设备设置',
    '앱 언어': '应用语言',
    '앱 정보': '应用信息',
    '앱 버전': '应用版本',
    'ZIP 파일로 저장': '保存为 ZIP 文件',
    'ZIP 파일에서 복원': '从 ZIP 文件恢复',
    '이메일 앱을 찾을 수 없어요': '找不到邮件应用',
    '반려동물': '宠物',
    '강아지': '狗狗',
    '고양이': '猫咪',
    '건강관리': '健康管理',
    '가이드': '指南',
    '홈': '首页',
    '일지': '日记',
    '알림': '提醒',
    '프로필': '档案',
    '설정': '设置',
    '서비스': '服务',
    '도움말': '帮助',
    '언어': '语言',
    '취소': '取消',
    '삭제': '删除',
    '저장하기': '保存',
    '저장': '保存',
    '추가': '添加',
    '선택': '选择',
    '확인': '确认',
    '기록': '记录',
    '예방접종': '疫苗接种',
    '병원 예약': '医院预约',
    '병원': '医院',
    '투약': '用药',
    '식사 시간': '进餐时间',
    '식사': '进餐',
    '일일 리마인더': '每日提醒',
    '리마인더': '提醒',
    '배변': '排泄',
    '컨디션': '状态',
    '체중': '体重',
    '음수': '饮水',
    '접종': '接种',
    '미용': '美容',
    '빗질': '梳毛',
    '산책': '散步',
    '메모': '备忘',
    '사진': '照片',
    '동영상': '视频',
    '미디어': '媒体',
    '카메라': '相机',
    '갤러리': '相册',
    '오늘': '今天',
    '이번 주': '本周',
    '전체': '全部',
    '필수': '必需',
    '권장': '推荐',
    '매월': '每月',
    '없음': '无',
    '보통': '普通',
    '완료': '完成',
    '미완료': '未完成',
    '미입력': '未填写',
    '미등록': '未注册',
    '이름': '姓名',
    '종류': '类型',
    '품종': '品种',
    '나이': '年龄',
    '성별': '性别',
    '수컷': '公',
    '암컷': '母',
    '중성화': '绝育',
    '기본 정보': '基本信息',
    '식별 정보': '识别信息',
    '마이크로칩': '微芯片',
    '등록번호': '登记号',
    '생년월일': '出生日期',
    '비용': '费用',
    '제목': '标题',
    '중요도': '重要程度',
    '일반': '普通',
    '중요': '重要',
  },
  'zh-TW': {
    '반려숨탄': '寵物 Sumtan',
    '반려동물 건강관리 앱': '寵物健康管理 App',
    '반려동물 건강 안내서': '寵物健康指南',
    '내 위치 기반 동물병원': '依目前位置尋找動物醫院',
    '주변 동물병원': '附近動物醫院',
    '주변 병원 찾기': '尋找附近醫院',
    '건강관리 가이드': '健康管理指南',
    '개인정보 처리방침': '隱私權政策',
    '데이터 관리': '資料管理',
    '데이터 내보내기': '匯出資料',
    '데이터 가져오기': '匯入資料',
    '피드백 보내기': '傳送意見回饋',
    '푸시 알림 허용': '允許推播通知',
    '기기 알림 권한 설정': '裝置通知權限設定',
    '기기 설정 사용': '使用裝置設定',
    '앱 언어': 'App 語言',
    '앱 정보': 'App 資訊',
    '앱 버전': 'App 版本',
    'ZIP 파일로 저장': '儲存為 ZIP 檔',
    'ZIP 파일에서 복원': '從 ZIP 檔還原',
    '이메일 앱을 찾을 수 없어요': '找不到電子郵件 App',
    '반려동물': '寵物',
    '강아지': '狗狗',
    '고양이': '貓咪',
    '건강관리': '健康管理',
    '가이드': '指南',
    '홈': '首頁',
    '일지': '日誌',
    '알림': '提醒',
    '프로필': '檔案',
    '설정': '設定',
    '서비스': '服務',
    '도움말': '說明',
    '언어': '語言',
    '취소': '取消',
    '삭제': '刪除',
    '저장하기': '儲存',
    '저장': '儲存',
    '추가': '新增',
    '선택': '選擇',
    '확인': '確認',
    '기록': '記錄',
    '예방접종': '預防接種',
    '병원 예약': '醫院預約',
    '병원': '醫院',
    '투약': '用藥',
    '식사 시간': '用餐時間',
    '식사': '用餐',
    '일일 리마인더': '每日提醒',
    '리마인더': '提醒',
    '배변': '排泄',
    '컨디션': '狀態',
    '체중': '體重',
    '음수': '飲水',
    '접종': '接種',
    '미용': '美容',
    '빗질': '梳毛',
    '산책': '散步',
    '메모': '備忘錄',
    '사진': '照片',
    '동영상': '影片',
    '미디어': '媒體',
    '카메라': '相機',
    '갤러리': '相簿',
    '오늘': '今天',
    '이번 주': '本週',
    '전체': '全部',
    '필수': '必須',
    '권장': '建議',
    '매월': '每月',
    '없음': '無',
    '보통': '普通',
    '완료': '完成',
    '미완료': '未完成',
    '미입력': '未填寫',
    '미등록': '未登錄',
    '이름': '名字',
    '종류': '類型',
    '품종': '品種',
    '나이': '年齡',
    '성별': '性別',
    '수컷': '公',
    '암컷': '母',
    '중성화': '絕育',
    '기본 정보': '基本資訊',
    '식별 정보': '識別資訊',
    '마이크로칩': '晶片',
    '등록번호': '登記號碼',
    '생년월일': '出生日期',
    '비용': '費用',
    '제목': '標題',
    '중요도': '重要程度',
    '일반': '一般',
    '중요': '重要',
  },
  'es': {
    '반려숨탄': 'Pet Sumtan',
    '반려동물 건강관리 앱': 'App de salud para mascotas',
    '반려동물 건강 안내서': 'Guía de salud para mascotas',
    '내 위치 기반 동물병원': 'Veterinarias cerca de tu ubicación',
    '주변 동물병원': 'veterinarias cercanas',
    '주변 병원 찾기': 'Buscar hospitales cercanos',
    '건강관리 가이드': 'Guía de salud',
    '개인정보 처리방침': 'Política de privacidad',
    '데이터 관리': 'Gestión de datos',
    '데이터 내보내기': 'Exportar datos',
    '데이터 가져오기': 'Importar datos',
    '피드백 보내기': 'Enviar comentarios',
    '푸시 알림 허용': 'Permitir notificaciones push',
    '기기 알림 권한 설정': 'Permisos de notificación del dispositivo',
    '기기 설정 사용': 'Usar ajustes del dispositivo',
    '앱 언어': 'Idioma de la app',
    '앱 정보': 'Información de la app',
    '앱 버전': 'Versión de la app',
    'ZIP 파일로 저장': 'Guardar como ZIP',
    'ZIP 파일에서 복원': 'Restaurar desde ZIP',
    '이메일 앱을 찾을 수 없어요': 'No se encontró una app de correo',
    '반려동물': 'mascota',
    '강아지': 'perro',
    '고양이': 'gato',
    '건강관리': 'cuidado de salud',
    '가이드': 'guía',
    '홈': 'Inicio',
    '일지': 'Diario',
    '알림': 'Alertas',
    '프로필': 'Perfil',
    '설정': 'Ajustes',
    '서비스': 'Servicios',
    '도움말': 'Ayuda',
    '언어': 'Idioma',
    '취소': 'Cancelar',
    '삭제': 'Eliminar',
    '저장하기': 'Guardar',
    '저장': 'Guardar',
    '추가': 'Añadir',
    '선택': 'Seleccionar',
    '확인': 'Confirmar',
    '기록': 'Registro',
    '예방접종': 'Vacunación',
    '병원 예약': 'Cita veterinaria',
    '병원': 'Veterinaria',
    '투약': 'Medicación',
    '식사 시간': 'Hora de comer',
    '식사': 'Comida',
    '일일 리마인더': 'Recordatorio diario',
    '리마인더': 'Recordatorio',
    '배변': 'Baño',
    '컨디션': 'Estado',
    '체중': 'Peso',
    '음수': 'Agua',
    '접종': 'Vacuna',
    '미용': 'Peluquería',
    '빗질': 'Cepillado',
    '산책': 'Paseo',
    '메모': 'Nota',
    '사진': 'Foto',
    '동영상': 'Video',
    '미디어': 'Multimedia',
    '카메라': 'Cámara',
    '갤러리': 'Galería',
    '오늘': 'Hoy',
    '이번 주': 'Esta semana',
    '전체': 'Todo',
    '필수': 'Obligatorio',
    '권장': 'Recomendado',
    '매월': 'Mensual',
    '없음': 'Ninguno',
    '보통': 'Normal',
    '완료': 'Completado',
    '미완료': 'Pendiente',
    '미입력': 'Sin ingresar',
    '미등록': 'Sin registrar',
    '이름': 'Nombre',
    '종류': 'Tipo',
    '품종': 'Raza',
    '나이': 'Edad',
    '성별': 'Sexo',
    '수컷': 'Macho',
    '암컷': 'Hembra',
    '중성화': 'Esterilización',
    '기본 정보': 'Información básica',
    '식별 정보': 'Identificación',
    '마이크로칩': 'Microchip',
    '등록번호': 'Número de registro',
    '생년월일': 'Fecha de nacimiento',
    '비용': 'Costo',
    '제목': 'Título',
    '중요도': 'Prioridad',
    '일반': 'Normal',
    '중요': 'Importante',
  },
  'fr': {
    '반려숨탄': 'Pet Sumtan',
    '반려동물 건강관리 앱': 'App de santé pour animaux',
    '반려동물 건강 안내서': 'Guide santé pour animaux',
    '내 위치 기반 동물병원': 'Cliniques vétérinaires près de vous',
    '주변 동물병원': 'cliniques vétérinaires proches',
    '주변 병원 찾기': 'Trouver des cliniques proches',
    '건강관리 가이드': 'Guide santé',
    '개인정보 처리방침': 'Politique de confidentialité',
    '데이터 관리': 'Gestion des données',
    '데이터 내보내기': 'Exporter les données',
    '데이터 가져오기': 'Importer les données',
    '피드백 보내기': 'Envoyer un avis',
    '푸시 알림 허용': 'Autoriser les notifications',
    '기기 알림 권한 설정': 'Autorisations de notification',
    '기기 설정 사용': 'Utiliser les réglages de l’appareil',
    '앱 언어': 'Langue de l’app',
    '앱 정보': 'Infos de l’app',
    '앱 버전': 'Version de l’app',
    'ZIP 파일로 저장': 'Enregistrer en ZIP',
    'ZIP 파일에서 복원': 'Restaurer depuis un ZIP',
    '이메일 앱을 찾을 수 없어요': 'Aucune app e-mail trouvée',
    '반려동물': 'animal',
    '강아지': 'chien',
    '고양이': 'chat',
    '건강관리': 'santé',
    '가이드': 'guide',
    '홈': 'Accueil',
    '일지': 'Journal',
    '알림': 'Alertes',
    '프로필': 'Profil',
    '설정': 'Réglages',
    '서비스': 'Services',
    '도움말': 'Aide',
    '언어': 'Langue',
    '취소': 'Annuler',
    '삭제': 'Supprimer',
    '저장하기': 'Enregistrer',
    '저장': 'Enregistrer',
    '추가': 'Ajouter',
    '선택': 'Sélectionner',
    '확인': 'Confirmer',
    '기록': 'Note',
    '예방접종': 'Vaccination',
    '병원 예약': 'Rendez-vous vétérinaire',
    '병원': 'Clinique',
    '투약': 'Médicament',
    '식사 시간': 'Heure du repas',
    '식사': 'Repas',
    '일일 리마인더': 'Rappel quotidien',
    '리마인더': 'Rappel',
    '배변': 'Selles',
    '컨디션': 'État',
    '체중': 'Poids',
    '음수': 'Eau',
    '접종': 'Vaccin',
    '미용': 'Toilettage',
    '빗질': 'Brossage',
    '산책': 'Promenade',
    '메모': 'Mémo',
    '사진': 'Photo',
    '동영상': 'Vidéo',
    '미디어': 'Média',
    '카메라': 'Caméra',
    '갤러리': 'Galerie',
    '오늘': 'Aujourd’hui',
    '이번 주': 'Cette semaine',
    '전체': 'Tout',
    '필수': 'Obligatoire',
    '권장': 'Conseillé',
    '매월': 'Mensuel',
    '없음': 'Aucun',
    '보통': 'Normal',
    '완료': 'Terminé',
    '미완료': 'Non terminé',
    '미입력': 'Non renseigné',
    '미등록': 'Non enregistré',
    '이름': 'Nom',
    '종류': 'Type',
    '품종': 'Race',
    '나이': 'Âge',
    '성별': 'Sexe',
    '수컷': 'Mâle',
    '암컷': 'Femelle',
    '중성화': 'Stérilisation',
    '기본 정보': 'Informations de base',
    '식별 정보': 'Identification',
    '마이크로칩': 'Puce électronique',
    '등록번호': 'Numéro d’enregistrement',
    '생년월일': 'Date de naissance',
    '비용': 'Coût',
    '제목': 'Titre',
    '중요도': 'Priorité',
    '일반': 'Normal',
    '중요': 'Important',
  },
  'de': {
    '반려숨탄': 'Pet Sumtan',
    '반려동물 건강관리 앱': 'App für Tiergesundheit',
    '반려동물 건강 안내서': 'Ratgeber für Tiergesundheit',
    '내 위치 기반 동물병원': 'Tierkliniken in Ihrer Nähe',
    '주변 동물병원': 'nahe Tierkliniken',
    '주변 병원 찾기': 'Kliniken in der Nähe suchen',
    '건강관리 가이드': 'Gesundheitsratgeber',
    '개인정보 처리방침': 'Datenschutzerklärung',
    '데이터 관리': 'Datenverwaltung',
    '데이터 내보내기': 'Daten exportieren',
    '데이터 가져오기': 'Daten importieren',
    '피드백 보내기': 'Feedback senden',
    '푸시 알림 허용': 'Push-Mitteilungen erlauben',
    '기기 알림 권한 설정': 'Mitteilungsberechtigungen des Geräts',
    '기기 설정 사용': 'Geräteeinstellungen verwenden',
    '앱 언어': 'App-Sprache',
    '앱 정보': 'App-Info',
    '앱 버전': 'App-Version',
    'ZIP 파일로 저장': 'Als ZIP speichern',
    'ZIP 파일에서 복원': 'Aus ZIP wiederherstellen',
    '이메일 앱을 찾을 수 없어요': 'Keine E-Mail-App gefunden',
    '반려동물': 'Haustier',
    '강아지': 'Hund',
    '고양이': 'Katze',
    '건강관리': 'Gesundheitspflege',
    '가이드': 'Ratgeber',
    '홈': 'Start',
    '일지': 'Tagebuch',
    '알림': 'Alarme',
    '프로필': 'Profil',
    '설정': 'Einstellungen',
    '서비스': 'Dienste',
    '도움말': 'Hilfe',
    '언어': 'Sprache',
    '취소': 'Abbrechen',
    '삭제': 'Löschen',
    '저장하기': 'Speichern',
    '저장': 'Speichern',
    '추가': 'Hinzufügen',
    '선택': 'Auswählen',
    '확인': 'Bestätigen',
    '기록': 'Eintrag',
    '예방접종': 'Impfung',
    '병원 예약': 'Tierarzttermin',
    '병원': 'Klinik',
    '투약': 'Medikament',
    '식사 시간': 'Fütterungszeit',
    '식사': 'Fütterung',
    '일일 리마인더': 'Tägliche Erinnerung',
    '리마인더': 'Erinnerung',
    '배변': 'Kot/Urin',
    '컨디션': 'Zustand',
    '체중': 'Gewicht',
    '음수': 'Wasser',
    '접종': 'Impfung',
    '미용': 'Pflege',
    '빗질': 'Bürsten',
    '산책': 'Spaziergang',
    '메모': 'Notiz',
    '사진': 'Foto',
    '동영상': 'Video',
    '미디어': 'Medien',
    '카메라': 'Kamera',
    '갤러리': 'Galerie',
    '오늘': 'Heute',
    '이번 주': 'Diese Woche',
    '전체': 'Alle',
    '필수': 'Pflicht',
    '권장': 'Empfohlen',
    '매월': 'Monatlich',
    '없음': 'Keine',
    '보통': 'Normal',
    '완료': 'Erledigt',
    '미완료': 'Nicht erledigt',
    '미입력': 'Nicht angegeben',
    '미등록': 'Nicht registriert',
    '이름': 'Name',
    '종류': 'Art',
    '품종': 'Rasse',
    '나이': 'Alter',
    '성별': 'Geschlecht',
    '수컷': 'Männlich',
    '암컷': 'Weiblich',
    '중성화': 'Kastration',
    '기본 정보': 'Grunddaten',
    '식별 정보': 'Identifikation',
    '마이크로칩': 'Mikrochip',
    '등록번호': 'Registrierungsnummer',
    '생년월일': 'Geburtsdatum',
    '비용': 'Kosten',
    '제목': 'Titel',
    '중요도': 'Priorität',
    '일반': 'Normal',
    '중요': 'Wichtig',
  },
  'ar': {
    '반려숨탄': 'بت سمتان',
    '반려동물 건강관리 앱': 'تطبيق رعاية صحة الحيوانات الأليفة',
    '반려동물 건강 안내서': 'دليل صحة الحيوانات الأليفة',
    '내 위치 기반 동물병원': 'عيادات بيطرية قريبة من موقعك',
    '주변 동물병원': 'عيادات بيطرية قريبة',
    '주변 병원 찾기': 'العثور على عيادات قريبة',
    '건강관리 가이드': 'دليل الرعاية الصحية',
    '개인정보 처리방침': 'سياسة الخصوصية',
    '데이터 관리': 'إدارة البيانات',
    '데이터 내보내기': 'تصدير البيانات',
    '데이터 가져오기': 'استيراد البيانات',
    '피드백 보내기': 'إرسال ملاحظات',
    '푸시 알림 허용': 'السماح بالإشعارات',
    '기기 알림 권한 설정': 'أذونات إشعارات الجهاز',
    '기기 설정 사용': 'استخدام إعدادات الجهاز',
    '앱 언어': 'لغة التطبيق',
    '앱 정보': 'معلومات التطبيق',
    '앱 버전': 'إصدار التطبيق',
    'ZIP 파일로 저장': 'حفظ كملف ZIP',
    'ZIP 파일에서 복원': 'استعادة من ملف ZIP',
    '이메일 앱을 찾을 수 없어요': 'لم يتم العثور على تطبيق بريد',
    '반려동물': 'حيوان أليف',
    '강아지': 'كلب',
    '고양이': 'قط',
    '건강관리': 'الرعاية الصحية',
    '가이드': 'دليل',
    '홈': 'الرئيسية',
    '일지': 'السجل',
    '알림': 'التنبيهات',
    '프로필': 'الملف',
    '설정': 'الإعدادات',
    '서비스': 'الخدمات',
    '도움말': 'المساعدة',
    '언어': 'اللغة',
    '취소': 'إلغاء',
    '삭제': 'حذف',
    '저장하기': 'حفظ',
    '저장': 'حفظ',
    '추가': 'إضافة',
    '선택': 'اختيار',
    '확인': 'تأكيد',
    '기록': 'سجل',
    '예방접종': 'تطعيم',
    '병원 예약': 'موعد بيطري',
    '병원': 'عيادة',
    '투약': 'دواء',
    '식사 시간': 'وقت الوجبة',
    '식사': 'وجبة',
    '일일 리마인더': 'تذكير يومي',
    '리마인더': 'تذكير',
    '배변': 'إخراج',
    '컨디션': 'الحالة',
    '체중': 'الوزن',
    '음수': 'الماء',
    '접종': 'تطعيم',
    '미용': 'العناية',
    '빗질': 'تمشيط',
    '산책': 'نزهة',
    '메모': 'ملاحظة',
    '사진': 'صورة',
    '동영상': 'فيديو',
    '미디어': 'وسائط',
    '카메라': 'الكاميرا',
    '갤러리': 'المعرض',
    '오늘': 'اليوم',
    '이번 주': 'هذا الأسبوع',
    '전체': 'الكل',
    '필수': 'إلزامي',
    '권장': 'موصى به',
    '매월': 'شهريًا',
    '없음': 'لا يوجد',
    '보통': 'عادي',
    '완료': 'مكتمل',
    '미완료': 'غير مكتمل',
    '미입력': 'غير مدخل',
    '미등록': 'غير مسجل',
    '이름': 'الاسم',
    '종류': 'النوع',
    '품종': 'السلالة',
    '나이': 'العمر',
    '성별': 'الجنس',
    '수컷': 'ذكر',
    '암컷': 'أنثى',
    '중성화': 'تعقيم',
    '기본 정보': 'المعلومات الأساسية',
    '식별 정보': 'معلومات التعريف',
    '마이크로칩': 'الشريحة',
    '등록번호': 'رقم التسجيل',
    '생년월일': 'تاريخ الميلاد',
    '비용': 'التكلفة',
    '제목': 'العنوان',
    '중요도': 'الأولوية',
    '일반': 'عادي',
    '중요': 'مهم',
  },
  'pt': {
    '반려숨탄': 'Pet Sumtan',
    '반려동물 건강관리 앱': 'App de saúde para pets',
    '반려동물 건강 안내서': 'Guia de saúde para pets',
    '내 위치 기반 동물병원': 'Hospitais veterinários perto de você',
    '주변 동물병원': 'hospitais veterinários próximos',
    '주변 병원 찾기': 'Encontrar hospitais próximos',
    '건강관리 가이드': 'Guia de saúde',
    '개인정보 처리방침': 'Política de privacidade',
    '데이터 관리': 'Gerenciamento de dados',
    '데이터 내보내기': 'Exportar dados',
    '데이터 가져오기': 'Importar dados',
    '피드백 보내기': 'Enviar feedback',
    '푸시 알림 허용': 'Permitir notificações push',
    '기기 알림 권한 설정': 'Permissões de notificação do dispositivo',
    '기기 설정 사용': 'Usar configurações do dispositivo',
    '앱 언어': 'Idioma do app',
    '앱 정보': 'Informações do app',
    '앱 버전': 'Versão do app',
    'ZIP 파일로 저장': 'Salvar como ZIP',
    'ZIP 파일에서 복원': 'Restaurar de um ZIP',
    '이메일 앱을 찾을 수 없어요': 'Nenhum app de e-mail encontrado',
    '반려동물': 'pet',
    '강아지': 'cão',
    '고양이': 'gato',
    '건강관리': 'cuidados de saúde',
    '가이드': 'guia',
    '홈': 'Início',
    '일지': 'Diário',
    '알림': 'Alertas',
    '프로필': 'Perfil',
    '설정': 'Configurações',
    '서비스': 'Serviços',
    '도움말': 'Ajuda',
    '언어': 'Idioma',
    '취소': 'Cancelar',
    '삭제': 'Excluir',
    '저장하기': 'Salvar',
    '저장': 'Salvar',
    '추가': 'Adicionar',
    '선택': 'Selecionar',
    '확인': 'Confirmar',
    '기록': 'Registro',
    '예방접종': 'Vacinação',
    '병원 예약': 'Consulta veterinária',
    '병원': 'Hospital',
    '투약': 'Medicação',
    '식사 시간': 'Hora da refeição',
    '식사': 'Refeição',
    '일일 리마인더': 'Lembrete diário',
    '리마인더': 'Lembrete',
    '배변': 'Evacuação',
    '컨디션': 'Condição',
    '체중': 'Peso',
    '음수': 'Água',
    '접종': 'Vacina',
    '미용': 'Banho e tosa',
    '빗질': 'Escovação',
    '산책': 'Passeio',
    '메모': 'Nota',
    '사진': 'Foto',
    '동영상': 'Vídeo',
    '미디어': 'Mídia',
    '카메라': 'Câmera',
    '갤러리': 'Galeria',
    '오늘': 'Hoje',
    '이번 주': 'Esta semana',
    '전체': 'Tudo',
    '필수': 'Obrigatório',
    '권장': 'Recomendado',
    '매월': 'Mensal',
    '없음': 'Nenhum',
    '보통': 'Normal',
    '완료': 'Concluído',
    '미완료': 'Não concluído',
    '미입력': 'Não informado',
    '미등록': 'Não registrado',
    '이름': 'Nome',
    '종류': 'Tipo',
    '품종': 'Raça',
    '나이': 'Idade',
    '성별': 'Sexo',
    '수컷': 'Macho',
    '암컷': 'Fêmea',
    '중성화': 'Castrado',
    '기본 정보': 'Informações básicas',
    '식별 정보': 'Identificação',
    '마이크로칩': 'Microchip',
    '등록번호': 'Número de registro',
    '생년월일': 'Data de nascimento',
    '비용': 'Custo',
    '제목': 'Título',
    '중요도': 'Prioridade',
    '일반': 'Normal',
    '중요': 'Importante',
  },
};

const _englishWordFallbackByLanguage = <String, Map<String, String>>{
  'ja': {
    'A professional health guide': '専門的な健康ガイド',
    'based on veterinary recommendations': '獣医師の推奨基準に基づいています',
    'Dog health care guide': '犬の健康管理ガイド',
    'Cat health care guide': '猫の健康管理ガイド',
    'Core vaccines': 'コアワクチン',
    'Non-core vaccines': '任意ワクチン',
    'Required': '必須',
    'Recommended': '推奨',
    'Monthly': '毎月',
    'Health guide': '健康管理ガイド',
    'Dog': '犬',
    'Cat': '猫',
    'Vaccination': '予防接種',
    'Parasite prevention': '寄生虫予防',
    'Heartworm': 'フィラリア',
    'External parasites': '外部寄生虫',
    'Internal parasites': '内部寄生虫',
    'Health checkups': '健康診断',
    'Emergency signs': '緊急サイン',
    'Nutrition': '栄養管理',
    'Dental care': '歯のケア',
    'Age': '年齢',
    'Checkup cycle': '健診周期',
    'Main items': '主な項目',
    'Exercise level': '運動量',
    'Breed examples': '犬種例',
    'Low': '低い',
    'Normal': '普通',
    'High': '高い',
    'Save': '保存',
    'Cancel': 'キャンセル',
    'Delete': '削除',
    'Add': '追加',
    'Edit': '編集',
    'Settings': '設定',
    'Profile': 'プロフィール',
    'Journal': '日誌',
    'Alerts': '通知',
    'Home': 'ホーム',
    'Help': 'ヘルプ',
    'Privacy policy': 'プライバシーポリシー',
    'Data export': 'データを書き出す',
    'Data import': 'データを読み込む',
    'Feedback': 'フィードバック',
    'Photos': '写真',
    'Videos': '動画',
    'Photo': '写真',
    'Video': '動画',
    'Camera': 'カメラ',
    'Gallery': 'ギャラリー',
    'Pet': 'ペット',
    'pet': 'ペット',
  },
  'zh-CN': {
    'A professional health guide': '专业健康指南',
    'based on veterinary recommendations': '基于兽医建议',
    'Dog health care guide': '狗狗健康管理指南',
    'Cat health care guide': '猫咪健康管理指南',
    'Core vaccines': '核心疫苗',
    'Non-core vaccines': '非核心疫苗',
    'Required': '必需',
    'Recommended': '推荐',
    'Monthly': '每月',
    'Health guide': '健康指南',
    'Dog': '狗狗',
    'Cat': '猫咪',
    'Vaccination': '疫苗接种',
    'Parasite prevention': '寄生虫预防',
    'Heartworm': '心丝虫',
    'External parasites': '外部寄生虫',
    'Internal parasites': '内部寄生虫',
    'Health checkups': '健康检查',
    'Emergency signs': '紧急症状',
    'Nutrition': '营养管理',
    'Dental care': '牙齿护理',
    'Age': '年龄',
    'Checkup cycle': '检查周期',
    'Main items': '主要项目',
    'Exercise level': '运动量',
    'Breed examples': '品种示例',
    'Low': '低',
    'Normal': '普通',
    'High': '高',
    'Save': '保存',
    'Cancel': '取消',
    'Delete': '删除',
    'Add': '添加',
    'Edit': '编辑',
    'Settings': '设置',
    'Profile': '档案',
    'Journal': '日记',
    'Alerts': '提醒',
    'Home': '首页',
    'Help': '帮助',
    'Privacy policy': '隐私政策',
    'Data export': '导出数据',
    'Data import': '导入数据',
    'Feedback': '反馈',
    'Photos': '照片',
    'Videos': '视频',
    'Photo': '照片',
    'Video': '视频',
    'Camera': '相机',
    'Gallery': '相册',
    'Pet': '宠物',
    'pet': '宠物',
  },
  'zh-TW': {
    'A professional health guide': '專業健康指南',
    'based on veterinary recommendations': '依據獸醫建議',
    'Dog health care guide': '狗狗健康管理指南',
    'Cat health care guide': '貓咪健康管理指南',
    'Core vaccines': '核心疫苗',
    'Non-core vaccines': '非核心疫苗',
    'Required': '必須',
    'Recommended': '建議',
    'Monthly': '每月',
    'Health guide': '健康指南',
    'Dog': '狗狗',
    'Cat': '貓咪',
    'Vaccination': '預防接種',
    'Parasite prevention': '寄生蟲預防',
    'Heartworm': '心絲蟲',
    'External parasites': '外部寄生蟲',
    'Internal parasites': '內部寄生蟲',
    'Health checkups': '健康檢查',
    'Emergency signs': '緊急症狀',
    'Nutrition': '營養管理',
    'Dental care': '牙齒護理',
    'Age': '年齡',
    'Checkup cycle': '檢查週期',
    'Main items': '主要項目',
    'Exercise level': '運動量',
    'Breed examples': '品種範例',
    'Low': '低',
    'Normal': '普通',
    'High': '高',
    'Save': '儲存',
    'Cancel': '取消',
    'Delete': '刪除',
    'Add': '新增',
    'Edit': '編輯',
    'Settings': '設定',
    'Profile': '檔案',
    'Journal': '日誌',
    'Alerts': '提醒',
    'Home': '首頁',
    'Help': '說明',
    'Privacy policy': '隱私權政策',
    'Data export': '匯出資料',
    'Data import': '匯入資料',
    'Feedback': '意見回饋',
    'Photos': '照片',
    'Videos': '影片',
    'Photo': '照片',
    'Video': '影片',
    'Camera': '相機',
    'Gallery': '相簿',
    'Pet': '寵物',
    'pet': '寵物',
  },
  'es': {
    'A professional health guide': 'Una guía profesional de salud',
    'based on veterinary recommendations':
        'basada en recomendaciones veterinarias',
    'Dog health care guide': 'Guía de salud para perros',
    'Cat health care guide': 'Guía de salud para gatos',
    'Core vaccines': 'Vacunas esenciales',
    'Non-core vaccines': 'Vacunas opcionales',
    'Required': 'Obligatorio',
    'Recommended': 'Recomendado',
    'Monthly': 'Mensual',
    'Health guide': 'Guía de salud',
    'Dog': 'Perro',
    'Cat': 'Gato',
    'Vaccination': 'Vacunación',
    'Parasite prevention': 'Prevención de parásitos',
    'Heartworm': 'Gusano del corazón',
    'External parasites': 'Parásitos externos',
    'Internal parasites': 'Parásitos internos',
    'Health checkups': 'Revisiones de salud',
    'Emergency signs': 'Señales de emergencia',
    'Nutrition': 'Nutrición',
    'Dental care': 'Cuidado dental',
    'Age': 'Edad',
    'Checkup cycle': 'Frecuencia',
    'Main items': 'Elementos principales',
    'Exercise level': 'Nivel de ejercicio',
    'Breed examples': 'Ejemplos de razas',
  },
  'fr': {
    'A professional health guide': 'Un guide santé professionnel',
    'based on veterinary recommendations':
        'fondé sur les recommandations vétérinaires',
    'Dog health care guide': 'Guide santé du chien',
    'Cat health care guide': 'Guide santé du chat',
    'Core vaccines': 'Vaccins essentiels',
    'Non-core vaccines': 'Vaccins optionnels',
    'Required': 'Obligatoire',
    'Recommended': 'Conseillé',
    'Monthly': 'Mensuel',
    'Health guide': 'Guide santé',
    'Dog': 'Chien',
    'Cat': 'Chat',
    'Vaccination': 'Vaccination',
    'Parasite prevention': 'Prévention des parasites',
    'Heartworm': 'Dirofilariose',
    'External parasites': 'Parasites externes',
    'Internal parasites': 'Parasites internes',
    'Health checkups': 'Bilans de santé',
    'Emergency signs': 'Signes d’urgence',
    'Nutrition': 'Nutrition',
    'Dental care': 'Soins dentaires',
    'Age': 'Âge',
    'Checkup cycle': 'Fréquence',
    'Main items': 'Points principaux',
    'Exercise level': 'Niveau d’exercice',
    'Breed examples': 'Exemples de races',
  },
  'de': {
    'A professional health guide': 'Ein professioneller Gesundheitsratgeber',
    'based on veterinary recommendations':
        'basierend auf tierärztlichen Empfehlungen',
    'Dog health care guide': 'Gesundheitsratgeber für Hunde',
    'Cat health care guide': 'Gesundheitsratgeber für Katzen',
    'Core vaccines': 'Kernimpfungen',
    'Non-core vaccines': 'Optionale Impfungen',
    'Required': 'Pflicht',
    'Recommended': 'Empfohlen',
    'Monthly': 'Monatlich',
    'Health guide': 'Gesundheitsratgeber',
    'Dog': 'Hund',
    'Cat': 'Katze',
    'Vaccination': 'Impfung',
    'Parasite prevention': 'Parasitenprophylaxe',
    'Heartworm': 'Herzwurm',
    'External parasites': 'Äußere Parasiten',
    'Internal parasites': 'Innere Parasiten',
    'Health checkups': 'Gesundheitschecks',
    'Emergency signs': 'Notfallzeichen',
    'Nutrition': 'Ernährung',
    'Dental care': 'Zahnpflege',
    'Age': 'Alter',
    'Checkup cycle': 'Untersuchungsintervall',
    'Main items': 'Wichtige Punkte',
    'Exercise level': 'Bewegungsbedarf',
    'Breed examples': 'Rassebeispiele',
  },
  'ar': {
    'A professional health guide': 'دليل صحي متخصص',
    'based on veterinary recommendations': 'مبني على توصيات بيطرية',
    'Dog health care guide': 'دليل رعاية صحة الكلاب',
    'Cat health care guide': 'دليل رعاية صحة القطط',
    'Core vaccines': 'اللقاحات الأساسية',
    'Non-core vaccines': 'اللقاحات الاختيارية',
    'Required': 'إلزامي',
    'Recommended': 'موصى به',
    'Monthly': 'شهريًا',
    'Health guide': 'دليل الصحة',
    'Dog': 'كلب',
    'Cat': 'قط',
    'Vaccination': 'التطعيم',
    'Parasite prevention': 'الوقاية من الطفيليات',
    'Heartworm': 'الدودة القلبية',
    'External parasites': 'طفيليات خارجية',
    'Internal parasites': 'طفيليات داخلية',
    'Health checkups': 'فحوصات صحية',
    'Emergency signs': 'علامات طارئة',
    'Nutrition': 'التغذية',
    'Dental care': 'العناية بالأسنان',
    'Age': 'العمر',
    'Checkup cycle': 'دورية الفحص',
    'Main items': 'العناصر الرئيسية',
    'Exercise level': 'مستوى النشاط',
    'Breed examples': 'أمثلة السلالات',
  },
  'pt': {
    'A professional health guide': 'Um guia profissional de saúde',
    'based on veterinary recommendations':
        'baseado em recomendações veterinárias',
    'Dog health care guide': 'Guia de saúde para cães',
    'Cat health care guide': 'Guia de saúde para gatos',
    'Core vaccines': 'Vacinas essenciais',
    'Non-core vaccines': 'Vacinas opcionais',
    'Required': 'Obrigatório',
    'Recommended': 'Recomendado',
    'Monthly': 'Mensal',
    'Health guide': 'Guia de saúde',
    'Dog': 'Cão',
    'Cat': 'Gato',
    'Vaccination': 'Vacinação',
    'Parasite prevention': 'Prevenção de parasitas',
    'Heartworm': 'Dirofilariose',
    'External parasites': 'Parasitas externos',
    'Internal parasites': 'Parasitas internos',
    'Health checkups': 'Check-ups de saúde',
    'Emergency signs': 'Sinais de emergência',
    'Nutrition': 'Nutrição',
    'Dental care': 'Cuidado dental',
    'Age': 'Idade',
    'Checkup cycle': 'Frequência',
    'Main items': 'Itens principais',
    'Exercise level': 'Nível de exercício',
    'Breed examples': 'Exemplos de raças',
  },
};

const _rawWordFallback = <String, String>{
  '반려숨탄': 'Pet Sumtan',
  '반려동물': 'pet',
  '강아지': 'dog',
  '고양이': 'cat',
  '건강관리': 'health care',
  '가이드': 'guide',
  '예방접종': 'vaccination',
  '알림': 'alert',
  '기록': 'record',
  '설정': 'settings',
  '프로필': 'profile',
  '일지': 'journal',
  '홈': 'home',
  '데이터': 'data',
  '내보내기': 'export',
  '가져오기': 'import',
  '삭제': 'delete',
  '저장': 'save',
  '취소': 'cancel',
  '추가': 'add',
  '선택': 'select',
  '확인': 'check',
  '병원': 'hospital',
  '식사': 'meal',
  '음수': 'water',
  '배변': 'potty',
  '체중': 'weight',
  '투약': 'medication',
  '미용': 'grooming',
  '산책': 'walk',
  '메모': 'memo',
  '사진': 'photo',
  '동영상': 'video',
  '카메라': 'camera',
  '갤러리': 'gallery',
  '오늘': 'today',
  '이번 주': 'this week',
  '전체': 'all',
  '필수': 'required',
  '권장': 'recommended',
  '매월': 'monthly',
  '보통': 'normal',
  '없음': 'none',
};
